### ISSUE TITLE
contextTypes properties and ES6 components

### ISSUE THREAD

**Issue by benjamindulau** [yahoo/fluxible#103]
Is it possible to use Fluxible with components written with ES6 syntax?
What are the guidelines here?

When writing React components with ES6, the state is initialized in the constructor.
At this point, I need to get my store instance.

For instance:

```javascript
class EntryPointController extends React.Component {
    constructor(props) {
        super(props);

        this.store = this.getStore(EntryPointStore);
        this.state = this.getState();
    }

    getState() {
        return {
            creationType: this.store.getCreationType()
        };
    }

    render() {
    }

    onChange() {
        this.setState(this.getState());
    }
}

EntryPointController.contextTypes = {
    getStore:      React.PropTypes.func.isRequired,
    executeAction: React.PropTypes.func.isRequired
};
EntryPointController.statics = {storeListeners: [EntryPointStore]};

module.exports = EntryPointController;
```

But I obviously get a `TypeError` when calling `this.getStore` in the constructor since this method is not assigned yet at this moment.

```
Uncaught TypeError: undefined is not a function
```

Thanks!

**Comment by jedireza** [comment]
In your constructor if you use `this.context.getStore(...)` does it still fail?

**Comment by mridgway** [comment]
With ES6 components, you will have to hook up the `componentDidMount` and `componentWillUnmount` to listen to the store and unlisten to the store respectively. We are planning to add the ability to wrap your components with a store listening wrapper that would pass your store data as props to your component. 

You can see examples of ES6 components with manual store listening at https://github.com/yahoo/flux-examples/blob/fluxible-router/fluxible-router/components/Application.js
You can see more on the wrapper proposal at #70.

**Comment by mridgway** [comment]
v0.4 now provides two higher-order components that should help with ES6 support: [provideContext](http://fluxible.io/api/addons/provideContext.html) and [connectToStores](http://fluxible.io/api/addons/connectToStores.html).

**Comment by benjamindulau** [comment]
@mridgway I'm sorry but I'm trying to update my ES6 code according to the last updates in fluxible, but I don't know why I don't get the context in my child components.

As stated in the doc, if I use the `context.createElement()` method, I don't need `provideContext` right?

That's how I'm trying do it:

```javascript
import React from 'react';
import Fluxible from 'fluxible';
import EntryPoint from './EntryPoint.react';
import CreateStore from './stores/CreateStore';

var app = new Fluxible({
    component: EntryPoint
});

app.registerStore(CreateStore);

var context = app.createContext();

React.render(
    context.createElement(),
    document.getElementById('app')
);
```

```javascript
class EntryPoint extends React.Component {
    render(): any {
        return <CreateForm />;
    }
}

export default EntryPoint;
```

```javascript
class CreateForm extends React.Component {

    store: CreateStore;

    constructor(props: Object) {
        super(props);
        this.state = this.getStateFromStore();
    }

    getStateFromStore(): Object {
        this.store = this.getStore(CreateStore);
        return {
            // whatever
        };
    }

    render(): any {
        // whatever
    }
}

CreateForm.contextTypes = {
    getStore:      React.PropTypes.func.isRequired,
    executeAction: React.PropTypes.func.isRequired
};

export default CreateForm;
```

But this gives me the following error:

```
Uncaught TypeError: this.getStore is not a function
```

**Comment by benjamindulau** [comment]
Hum wait a minute, I'm reading the documentation again ;-)

**Comment by benjamindulau** [comment]
Ok so now I'm pretty sure I did it like stated in the doc. I just update my `EntryPoint` component like the following:

```
class EntryPoint extends React.Component {
    render(): any {
        return <CreateForm />;
    }
}

EntryPoint = provideContext(EntryPoint);
export default EntryPoint;
```

And since I'm using `context.createElement()`, the context should automatically be provided to my component.

But `this.context` still is `undefined` in the `CreateForm` component. Is `connectToStores` factory mandatory?

**Comment by mridgway** [comment]
Hmm, your usage of `provideContext` and `contextTypes` in `CreateForm` look correct to me. Not sure why you'd be getting context as undefined. Just to make sure, do you have any `npm link`ed modules locally? We've seen issues with context being broken with npm link.

**Comment by benjamindulau** [comment]
Nope, I don't have any. I work on a Vagrant VM where the files are shared from my host to the VM with NFS but I doubt that it could cause that kind of issue.

Do I create the context the right way? `var context = app.createContext();`

**Comment by benjamindulau** [comment]
I just looked into my `EntryPoint` component in debug mode, and it gets the context correctly. It's just not automatically provided to the children.

**Comment by mridgway** [comment]
That's baffling. `contextTypes` on `CreateForm` tells its parent to propagate those keys. Just to make sure, you're using `this.context.getStore` instead of `this.getStore` right?

**Comment by benjamindulau** [comment]
Both are undefined. Now I'm basically trying to log `this.context` in the `CreateForm` component constructor and it's `undefined`.

**Comment by benjamindulau** [comment]
I'm gonna try to create a new dummy project with 2 simple components to see what happens.

**Comment by benjamindulau** [comment]
Ok, something is wrong in my code, this works:

```javascript
import React from 'react';
import Fluxible from 'fluxible';
import provideContext from 'fluxible/addons/provideContext';

class Application extends React.Component {
    render() {
        return (
            <div>
                <DummyComponent />
            </div>
        );
    }
}

Application = provideContext(Application);

class DummyComponent extends React.Component {
    componentDidMount() {
        console.log(this.context);
    }

    render() {
        return <p>dummy test</p>;
    }
}

DummyComponent.contextTypes = {
    getStore:      React.PropTypes.func.isRequired,
    executeAction: React.PropTypes.func.isRequired
};

var app = new Fluxible({
    component: Application
});

var context = app.createContext();

React.render(
    context.createElement(),
    document.getElementById('app')
);
```

I get the context in the console logs.

Investigating.... ;-)

**Comment by benjamindulau** [comment]
Ok, got something interesting, in my dummy test above: `this.context` is undefined in the `constructor` but correctly defined in `componentDidMount` ;-)

Any idea?

**Comment by benjamindulau** [comment]
Ok I figured it out after a walk ;-)

I can get the context this way:

```javascript
class CreateForm extends React.Component {

    store: CreateStore;

    constructor(props: Object, context: Object) {
        super(props, context);
        this.state = this.getStateFromStore();
    }
}

CreateForm.contextTypes = {
    getStore:      React.PropTypes.func.isRequired,
    executeAction: React.PropTypes.func.isRequired
};
```

The context needs to get passed as a constructor argument.
This [issue in react-router](https://github.com/rackt/react-router/issues/1059) pointed me out in the right direction.

I think this deserves to be documented somewhere in the Fluxible documentation ;-)
BTW, did you get a working code just like it's described in the documentation right now?
