### ISSUE TITLE
Aliases to Dispatch

### ISSUE THREAD

**Issue by arb** [yahoo/fluxible#104]
What do you think about aliasing `dispatch` to things like `emit` or `trigger`? As someone new to this ecosystem, using a different verb for basically event emitter nomenclature ads a bit of learning overhead. You could do this in your own project at startup, but just curious what the thoughts were on adding that to the core.

**Comment by mridgway** [comment]
`dispatch` is the name that Flux uses and we intend to stick with. Having aliases would probably be confusing for people that are coming from stock Flux.
