### ISSUE TITLE
Question about routing

### ISSUE THREAD

**Issue by lance-anderson** [yahoo/fluxible#105]
I'm trying to understand routing using Fluxible. The tutorial: http://fluxible.io/tutorials/routing.html demonstrates how to load two different pages using the ```Home.jsx``` component and the ```About.jsx``` component.

And then there is the Application class which handles the rendering of the components.

```
var Application = React.createClass({
    mixins: [ FluxibleMixin ],
    getInitialState: function () {
        return this.getStore(ApplicationStore).getState();
    },
    render: function (){
        return (
            <div>
                {'home' === this.state.currentPageName ? <Home/> : <About/>}
            </div>
        );
    }
});
```

Specifically, it's this bit of code that confuses me:
```
                {'home' === this.state.currentPageName ? <Home/> : <About/>}
```

Using a "pageName" to toggle which component to load feels clunky. I guess it's fine if you only have a couple of pages but that sure doesn't scale out very well.

Even something like this would be slightly less clunky:

```
module.exports = {
    home: {
        path: '/',
        method: 'get',
        label: 'Home',
        page: 'home',
        component: HomeComponent
    },
    about: {
        path: '/about',
        method: 'get',
        label: 'About',
        page: 'about',
        component: AboutComponent
    }
};
```

Having to manually match the routes to the components is clunky as well but at least a little less clunky.

Am I missing something? Seems like there should be a plugin or something that auto-magically takes a route and matches it up with a JSX component.

**Comment by jedireza** [comment]
Thanks for opening an issue.

 > Using a "pageName" to toggle which component to load feels clunky. I guess it's fine if you only have a couple of pages but that sure doesn't scale out very well.

I agree. The work @mridgway is doing with https://github.com/yahoo/flux-router-component/pull/81 should clean this up nicely. He did something similar to your `component` idea in the route config but it's called `handler` in that PR.

**Comment by lance-anderson** [comment]
Thanks for getting back to me. I'll take a look at what @mridgway has written. To be clear, what would make the most sense is an autoloader that is configured with a base path, takes a route, and looks for a JSX component to load. If a matching JSX component isn't found it throws a 404.

**Comment by redonkulus** [comment]
fluxible-router supports handlers now, as @jedireza mentioned. Please try that out and let us know how it goes. https://github.com/yahoo/fluxible-router/blob/master/docs/quick-start.md
