### ISSUE TITLE
Proposal: Add `provideContext` higher-order component method

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#107]
## `contextProvider(Component, customContextTypes)`

This would be an alternative method to `FluxibleComponent` for providing your application with the React context using a higher-order component similar to [`connectToStores`](https://github.com/yahoo/fluxible/issues/70).

### Providing context with `FluxibleComponent`:

```js
var Application = React.createClass({
    contextTypes: {
        executeAction: React.PropTypes.func.isRequired,
        getStore: React.PropTypes.func.isRequired
    }
    ...
});

React.renderToString(
    <FluxibleComponent context={context}>
        <Application />
    </FluxibleComponent>
);
```

### Providing context with `provideContext`:

```js
var Application = React.createClass({
    contextTypes: {
        executeAction: React.PropTypes.func.isRequired,
        getStore: React.PropTypes.func.isRequired
    }
    ...
});

Application = provideContext(Application);

React.renderToString(<Application context={context} />);
```

This would also allow providing custom `childContextTypes` if you have your own plugin. For instance, adding `foo` to component context:

```js
Application = provideContext(Application, {
    foo: React.PropTypes.func
});
```

The `customContextTypes` would get merged with Fluxible's built-in `contextTypes`: `executeAction` and `getStore`.

### Implementation

```js
var React = require('react');
var objectAssign = require('object-assign');

module.exports = function provideContext(Component, customContextTypes) {
    var childContextTypes = objectAssign({
        executeAction: React.PropTypes.func.isRequired,
        getStore: React.PropTypes.func.isRequired
    }, customContextTypes || {});

    var ContextProvider = React.createClass({
        displayName: 'ContextProvider',

        propTypes: {
            context: React.PropTypes.object.isRequired
        },

        childContextTypes: childContextTypes,

        getChildContext: function () {
            var childContext = {
                executeAction: this.props.context.executeAction,
                getStore: this.props.context.getStore
            };
            if (customContextTypes) {
                Object.keys(customContextTypes).forEach(function (key) {
                    childContext[key] = this.props.context[key];
                }, this);
            }
            return childContext;
        },

        render: function () {
            return React.createElement(Component, this.props);
        }
    });

    return ContextProvider;
};
```

**Comment by igorbt** [comment]
I just got into a problem with contexts and you proposal may fix it. The problem is that I cannot access properties that plugins add to component context (with `plugComponentContext`). In my case it was `RoutrPlugin.makePath`.
According to your proposal I could do something like:
```javascript
Application = provideContext(Application, {
    makePath: React.PropTypes.func
});
```
But I should then whitelist all props that plugins already made available to components. While it's not the biggest problem in the world, it still isn't elegant.

Note that one may be confused of the term "context". Because there is a "react context" and a "fluxible context".

What I propose is that we just should make "fluxible context" available in "react context" as is. Maybe we can let some convenience methods like `getStore` and `executeAction` (and let it be also backward compatible), but otherwise we shouldn't whitelist props.

What I tried in FluxibleMixin and it worked:

```javascript
var FluxibleMixin = {

    contextTypes: {
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func,
        fluxibleContext: React.PropTypes.object
    },

    // @todo: remove child context and encourage use of the FluxibleComponent
    childContextTypes: {
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func,
        fluxibleContext: React.PropTypes.object
    },

    /**
     * Provides the current context as a child context
     * @method getChildContext
     */
    getChildContext: function(){
        var context = {};
        Object.keys(FluxibleMixin.childContextTypes).forEach(function (key) {
            if (key === 'fluxibleContext') {
                context[key] = this.props.context || this.context;
            } else {
                context[key] = (this.props.context && this.props.context[key]) || this.context[key];
            }
        }, this);
        return context;
    },
...
```
Or, if I would implement this in your proposal:

```javascript
var React = require('react');

module.exports = function provideContext(Component) {
    var childContextTypes = {
        executeAction: React.PropTypes.func.isRequired,
        getStore: React.PropTypes.func.isRequired,
        fluxibleContext: React.PropTypes.object
    };

    var ContextProvider = React.createClass({
        displayName: 'ContextProvider',

        propTypes: {
            context: React.PropTypes.object.isRequired
        },

        childContextTypes: childContextTypes,

        getChildContext: function () {
            var childContext = {
                executeAction: this.props.context.executeAction,
                getStore: this.props.context.getStore,
                fluxibleContext: React.PropTypes.object
            };
            if (customContextTypes) {
                Object.keys(customContextTypes).forEach(function (key) {
                    if (key === 'fluxibleContext') {
                        childContext[key] = this.props.context;
                    } else {
                        childContext[key] = this.props.context[key];
                    }
                }, this);
            }
            return childContext;
        },

        render: function () {
            return React.createElement(Component, this.props);
        }
    });

    return ContextProvider;
};

```

Maybe we cal let `customContextTypes`, but I cannot think of a real use-case for it other than plugin props.

**Comment by mridgway** [comment]
Yes, this is exactly the problem that the `customContextTypes` can help with. The built-in helpers can't statically declare the `contextTypes` that you add to the component context via plugins, so this provides a mechanism for adding them. I could imagine that plugins could export their `contextTypes` to make it easy to do something like this:

```js
Application = provideContext(
    Application, 
    objectAssign({}, routrPlugin.contextTypes, fooPlugin.contextTypes)
);
```

(btw [fluxible-router](https://github.com/yahoo/flux-router-component/pull/81) will not extra contextTypes any more)

**Comment by igorbt** [comment]
@mridgway, sorry about the third code snippet in my previous comment. It probably confused you. I was in a hurry. Now I edited the comment and corrected the code. I hope that now it make more sense and you may review my proposal.

(thx for heads-up about fluxible-router)

**Comment by mridgway** [comment]
I understand the desire to make it easier to propagate as many context types as you want, but in my opinion circumventing the `contextTypes` by having one container for all of them goes against the way context is supposed to work. 

By having all of the context as a shallow object, it's also more clear when you are missing a plugin that a component depends on, because you will see the error message "Warning: Failed Context Types: Required context `foo` was not specified in `Component`. Check the render method of `ContextProvider`." Without specifying the `contextTypes` you could have a transient error that would be difficult to debug.

**Comment by igorbt** [comment]
@mridgway, thanks for explaining. It make sense.
