### ISSUE TITLE
Angular and custom view layer/components

### ISSUE THREAD

**Issue by igorbt** [yahoo/fluxible#127]
Could Fluxible work with other view layers beside React? Like Angular or even custom view layer?

We are trying to think about migrating our existing (BIG) application that has a lot of legacy modules (vanilla JS, Angular, jQueryUI) to Flux architecture using Fluxible. Ideally this would be an iterative migration. Do you think it is possible to have a Fluxible app mixed with non-React components? Can we make our non-React components to be integrated in the Flux data flow (listen to change events from Stores and trigger actions)? Or even more, can we let legacy components outside of Flux data flow and migrate them one by one?

Theoretically, I think all this should be possible. Do you see some impediments?

**Comment by mridgway** [comment]
There is very little within Fluxible core that uses React. Really the only thing that uses it is the `FluxibleContext.createElement()` method and the addons (which are not bundled with the main export). So yes, it should be very easy to use Fluxible without React.

**Comment by igorbt** [comment]
Great! I will try to experiment with this and I could post here if there are some impediments.
