### ISSUE TITLE
Upgrade guide Needed!

### ISSUE THREAD

**Issue by edygar** [yahoo/fluxible#128]
Breaking changes are tough, very tough, and on `react-router` repo, they have an Upgrade guide that save us a lot of time and explains very well the reasons behind every change. I do [recommend the model](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md)

**Comment by cesarandreu** [comment]
Have you checked out the [CHANGELOG](https://github.com/yahoo/fluxible/blob/master/CHANGELOG.md)? At least for me so far, it's covered my needs.

**Comment by edygar** [comment]
I did but it misses a lot of the points that have driven the versions changes, as for example, `React.withContext`'s deprecation by React has lead to the formulation of `provideContext` and `FluxibleComponent`, which is now the way to contextfy the App. And so on, with little phrases like that plus the old and new way of doing things, the Upgrade guide could help saving a lot of time.

**Comment by ran-y** [comment]
agree with edygar, an Upgrade guide would be awesome.

**Comment by mridgway** [comment]
We will try to do better with an upgrade guide in the next versions. If someone is interested in providing an upgrade guide for 0.3->0.4, that would be much appreciated.

**Comment by jenswegar** [comment]
+1 for this. It becomes very confusing for a newbie like me when the guides seem to reference different versions of the library. E.g. the intro guide here http://fluxible.io/api/bringing-flux-to-the-server.html does give a good overview of the philosophy behind fluxible, however the code examples apparently are outdated (cloning the git repo for the intro guide downloads v. 0.1.5 of fluxible, we're at 0.4.10). With an upgrade guide, then at least I would be able to change the examples as needed even if the original tutorial/introduction is not yet quite up to date...

**Comment by mridgway** [comment]
We have started an upgrade guide for the 0.4->0.5 changes and will continue to do so for the next BC breaking releases.
