### ISSUE TITLE
warning es6-promises (package vertx do not exists)

### ISSUE THREAD

**Issue by seeden** [yahoo/fluxible#138]
Hi

I can see this error with webpack. 
The problem is that es6-promise is using package named vertx. But this package do not exists. Are u sure, that you chossed a good library for that?

WARNING in ./~/fluxible/~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in node_modules\fluxible\node_modules\es6-promise\dist  @ ./~/fluxible/~/es6-promise/dist/es6-promise.js 125:20-30

**Comment by gpbl** [comment]
I also have this problem because of [this issue](https://github.com/jakearchibald/es6-promise/issues/100).

**Comment by seeden** [comment]
Thanks @gpbl for temporary fix

**Comment by mridgway** [comment]
Looks like the relevant issue in es6-promise has been closed. I ran install and did not see the error any more.

**Comment by cesarandreu** [comment]
Still screws up with webpack for me :(. I had to keep `new webpack.IgnorePlugin(/vertx/)` in my plugin list.

**Comment by cesarandreu** [comment]
es6-promise just released a new version with the browser field in package.json, and the warning no longer happens :D. I think it's alright to close this.

**Comment by mridgway** [comment]
\m/

**Comment by growlsworth** [comment]
Issue is resolved on my machine as well. Thanks for the update.
