### ISSUE TITLE
`executeAction` no longer uses `setImmediate` to call action

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#139]
* should also warn if dispatcher is currently dispatching

**Comment by bruderstein** [comment]
Whilst things were "easier" with setImmediate, it hid cascading updates, which are a hint that something is possibly not quite optimal (I believe!).  Would you consider a pull request that checked (if NODE_ENV !== 'production') *before* setImmediate, if the dispatchr is currently dispatching, and if so issue a console warning (or a debug() output)?

**Comment by mridgway** [comment]
@bruderstein I like it. Yes.

**Comment by bruderstein** [comment]
PR on the way.  I want to try it first on our project tomorrow to check it works as the tests say it should :)

**Comment by technicallyfeasible** [comment]
I am currently using a structure where I have 2 stores, one that holds filter values and one that makes calls to a data source using the current filters. When the filters are updated through the user interface then the list component listens to that and dispatches another action to update the data source.

So yes, I think in this case it is legitimate to execute an action within the store dispatch of another action.

setImmediate unfortunately hides this call chain but I can live with that. Or is there a better way to do this?

**Comment by bruderstein** [comment]
With Async call stacks in chrome, you can still see the call chain for scenarios like these.
