### ISSUE TITLE
Add tests to examples

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#14]
What is the best approach/tool to test isomorphic fluxible-app applications? do you recommend Jest?
Would be great if you added some tests to your examples...

**Comment by jiyinyiyong** [comment]
I'm intereted in this topic too :smile:

**Comment by redonkulus** [comment]
FYI, we will be adding functional tests to our fluxible.io site prior to tackling this. You can watch https://github.com/yahoo/fluxible.io/issues/53 to stay up to date.

**Comment by kilometers** [comment]
Could someone offer a specific example on testing stores. I'm having trouble instantiating them for tests.

**Comment by Vijar** [comment]
@kilometers to instantiate stores for tests, I do something like this in mocha unit tests.

```js
var MyStore = require('./stores/MyStore.js');
var storeInstance;
beforeEach(function () {
    storeInstance = new MyStore();
});
```

Then in your tests you can call all the methods want to test on the `storeInstance`.

**Comment by kilometers** [comment]
Snap! Elegant. I'm burning my previous approach. With fire.

**Comment by redonkulus** [comment]
To follow up, @kilometers you can take a look at https://github.com/yahoo/fluxible.io/tree/master/tests/unit
