### ISSUE TITLE
Adding authentication to Fluxible apps

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#140]
What is the best way to add authentication to my Fluxible apps? Are there already some plugins available for that? or we should use an npm package like `passport` ?

**Comment by mridgway** [comment]
I would still use something like passport and then use a plugin to provide access to the user data or execute an action with the user data before calling the `navigate` action. This data would then be dehydrated and rehydrated to the client so you'd still have access to it on subsequent calls on the client.

**Comment by ali1k** [comment]
thank @mridgway . I could manage to handle it for now in the way you suggested: https://github.com/ali1k/risis

However, to apply access levels to different content/components, I still need to figure out a more flexible approach. I have to restrict dehydration and rehydration based on the credentials; and also handle access level on services. From my point of view, navigation/router component should inherently address this somehow.
I guess we can close this issue for now.
