### ISSUE TITLE
connectToStores: getStateFromStores - 'stores' contents get mangled by Uglify

### ISSUE THREAD

**Issue by Ambroos** [yahoo/fluxible#143]
Consider this code:

```javascript
// FooStore.js
class FooStore extends BaseStore {
    // ...
}
FooStore.storeName = 'FooStore';

// BarStore.js
let BarStore = createStore({
    storeName: 'BarStore'
});
export default BarStore;

// MyStore.js
var MyStore = function (dispatcherInterface) {
    BaseStore.apply(this, arguments);
};
inherits(MyStore, BaseStore);
MyStore.storeName = 'MyStore';
export default MyStore;

// Component.jsx
Component = connectToStores(Component, [FooStore, BarStore, MyStore], function (stores, props) {
    return {
        foo: stores.FooStore.getFoo(), // stores.FooStore = undefined
        bar: stores.BarStore.getBar(), // stores.BarStore = ok
        thing: stores.MyStore.getThing() // stores.MyStore = ok
    };
});
```

Without Uglification (default settings), `stores.FooStore`, `stores.BarStore` and 'stores.MyStore' work fine. After Uglifying with default settings, `stores.FooStore` will be undefined, `stores.BarStore` and `stores.MyStore` will work fine.

Stores extending BaseStore with ES6 classes using Babel get turned into named functions. Extending BaseStore like in the MyStore example creates an anonymous function, and  createStore seems to do the same behind the scenes. 

Now in connectToStores, this happens:

```javascript
stores.forEach(function (store) {
    var storeName = store.name || store.storeName || store;
    storeInstances[storeName] = this.context.getStore(store);
}, this);
return getStateFromStores(storeInstances, this.props);
```

Stores made with `createStore` or the 'manual' way to extend `BaseStore` will be anonymous functions, so for them their `storeName` will be used. For stores made with `class Store extends BaseStore`, `store.name` will exist and be set to the class name. However, Uglify mangles the name by default and the store will be available in `storeInstances` with the mangled name only.

I think taking `store.name` out of the `storeName` is enough to fix this. `Function.name` is unreliable after Uglify in any case. Maybe add a check to the store registration when `process.env.NODE_ENV !== 'production'` to see if the `storeName` property was set?

**Comment by mridgway** [comment]
That's unfortunate. You're right, `store.name` is unsafe to use when minified. I agree, we may have to remove support for that and enforce using a static `storeName` property.

**Comment by Ambroos** [comment]
```javascript
Dispatcher.prototype.getStoreName = function getStoreName(store) {
    if ('string' === typeof store) {
        return store;
    }
    return store.storeName || store.name;
};
```

Dispatchr prefers `store.storeName` over `store.name`, which sort-of-solves the problem (as long as the Store has storeName set). But I'm not sure if it's a good idea to support `store.name` at all. Everyone should/will Uglify their production/browser code at one point, it's not the easiest error to debug and it may just be better to enforce `storeName`.

**Comment by ali1k** [comment]
I experienced the same issue when using Uglification which was very annoying! 
Would be great if you put in the Grunt file, tasks for production (maybe with uglification settings that work with current babel-loader).

**Comment by woutderooms** [comment]
I found a way around this by editing the `addons/connectToStores`. I gave store.storeName first preference in the disjunction on the following line:

```javascript
var storeName = store.name || store.storeName || store;
```
is now:
```javascript
var storeName = store.storeName || store.name || store;
```

I do not however know what side-effect this might imply.

**Comment by mridgway** [comment]
@woutderooms That should be fine actually. We should make this change in dispatchr and in non-production environments warn if `store.storeName is not set`. In this case I think warning without a minor version bump is ok since this could cause issues for people.

In theory, using `store.name` would still work if you use uglify with the `--keep-fnames` but that would reduce a lot of optimization that you get from uglifying.

**Comment by mridgway** [comment]
This has been fixed and published. I have also pushed a warning message to dispatchr when using `store.name`.
