### ISSUE TITLE
Move fluxible/addons to new package

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#148]
The API for the addons is in more flux than the core library and should be versioned separately.

Each one could be it's own package, but I think it's still useful to have a cohesive addons package: `fluxible-addons`.

**Comment by mridgway** [comment]
It might be good to move `context.createElement` into an addon as well since it's not used in by all users (with react-router for example) and it depends on addons/React.

**Comment by cesarandreu** [comment]
I think this is a great idea! +1
I'm one of those react-router users that isn't using `context.createElement`.

**Comment by alexaivars** [comment]
+1 Great Idea! I think this might also make it possible to remove any react dependancies and make it possible to use fluxible in react-native.

**Comment by mridgway** [comment]
@alexaivars That is indeed one of the motivating factors for this.

**Comment by mridgway** [comment]
It seems we should add "react" to the package name, since it will only work with "react". A separate package may be needed for addons specifically for react-native. I'm thinking `fluxible-plugins-react` and `fluxible-plugins-react-native` for now. I'm hoping react 0.14 will help with bridging the gap between the two.

**Comment by mridgway** [comment]
New package created here: https://github.com/yahoo/fluxible-addons-react
PR for updating Fluxible to use new package with warnings: #202
