### ISSUE TITLE
connectToStores design decisions

### ISSUE THREAD

**Issue by benjamindulau** [yahoo/fluxible#154]
I don't really like the new way stores states are now passed as component props.

It just doesn't feel right to access component state through props. It feels too far from the original React/Flux philosophy.

I'm interested in understanding what motivated this choice. I liked the way it was working with the `storeListeners` property defined in `statics` before.

**Comment by mridgway** [comment]
Higher order components are motivated by React moving towards ES6 classes which do not have a mixin solution. The best write up of this is here: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by benjamindulau** [comment]
Ok, I already read a lot about this pattern. It makes a lot of sense. It just feels weird at first to have the state hidden by the higher component.

But all things considered,mixin replacement aside, it also makes sense to get the store data as props and to not mix the component local state with the stores states. This somewhat protect these data since we can't change them accidentally by updating the component state. I remember some scenarios where I have some weird behavior because I had a bad merge between store state and local state.

Ok, now I just have to update a lot of code ;-)

**Comment by x1a0** [comment]
Good question and thanks for the answer. I had same strange feeling about only using `props` in my component. But it seems to be a good move!
