### ISSUE TITLE
Add more useful parameter validation

### ISSUE THREAD

**Issue by cesarandreu** [yahoo/fluxible#159]
I remember seeing [invariant](https://github.com/zertosh/invariant) mentioned in [another issue](https://github.com/yahoo/fluxible/commit/39346ea9818f133486ab817f7d94f9b645309efd). I'd love Fluxible to include better errors as well.

Sometimes I'll make a typo and end up passing `undefined` to `executeAction`. Then the error message will be `Cannot call method 'displayName' of undefined`, which isn't helpful at all. Then I'll look at the file where the exception came from and I'll be able to guess at why the error happened. But it's a lot nicer when you get a useful error. This is something that's bitten me a few times.

Thoughts? I can make a PR.

**Comment by cesarandreu** [comment]
Something that would make it even better, if the error told you where executeAction got called from. There's [Function.caller](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller), but I haven't used it before and I don't know if there's any dragons to be weary of.

I found a few existing modules:

* [caller](https://www.npmjs.com/package/caller)
* [caller-path](https://www.npmjs.com/package/caller-path)
* [callsite](https://github.com/tj/callsite)

No idea how well they work across browsers. Anyone have experience with this?

**Comment by mridgway** [comment]
Yeah, we definitely need some better error handling in some cases. I'm fine with using invariant :+1:

**Comment by mridgway** [comment]
I will add some more error checking for the issues you mentioned above. At this time I'm not sure we'll get a lot out of using invariant vs. what we're doing now.
