### ISSUE TITLE
Client side rendering only

### ISSUE THREAD

**Issue by ptomasroos** [yahoo/fluxible#161]
Hey!

I was wondering if there is a chance that following use-case is supported:
Skip the server side rendering from a fluxible app, and only send the state / api responses in serialised form.

We have a app that is heavily depending on screen sizes ect which can not be aligned with media queries ect and want to use the feature of a single response to a client with the data that's needed before rendering and the routing ofc of what should be invoked at what url.

But skipping the server side rendering and letting it be boostrapped + rendered on the client.

Takes?

**Comment by ptomasroos** [comment]
https://github.com/yahoo/flux-examples/blob/master/chat/server.js#L59
https://github.com/yahoo/flux-examples/blob/master/chat/components/Html.jsx#L31

Would removing those be enough? Anyone tried the use-case?

**Comment by mridgway** [comment]
In theory, yes, removing the markup from both HTML.jsx and server.js should give you what you want. Haven't tried it directly myself yet though.

**Comment by ptomasroos** [comment]
I will give it a try and report back @mridgway !

**Comment by agrippanux** [comment]
I tried it - works quite well (just have to remove what @mridgway suggested)

Of course now you are now using the client to render :)

**Comment by ptomasroos** [comment]
Which can be a perfect thing if you're depending on libraries written for the browser only :) :+1:

**Comment by ptomasroos** [comment]
Lets close this! Since it works.

**Comment by ccolonna** [comment]
Hi, need this, but 

> 
> 
> https://github.com/yahoo/flux-examples/blob/master/chat/server.js#L59 https://github.com/yahoo/flux-examples/blob/master/chat/components/Html.jsx#L31
> 
> Would removing those be enough? Anyone tried the use-case?

Hi, I need this, but links are not alive anymore. Can you give help ? Many thanks!
