### ISSUE TITLE
React native initialization

### ISSUE THREAD

**Issue by AbrahamAlcaina** [yahoo/fluxible#171]
Hey, I try to use it with react native.

But I don't have idea how intializate it,
I created a Fluxible instance, after that I created a context (FluxibleContext). 

Fluxible App
```javascript
import Fluxible from 'fluxible';
import ThemesStore from '../themes/stores/themeStore';
import QuestionsStore from '../questions/stores/questionsStore';
import App from './app.jsx';

const fluxibleApp = new Fluxible({
	component: App,
    stores: [ThemesStore, QuestionsStore]
});

fluxibleApp.registerStore(ThemesStore);

export default fluxibleApp;
```

Initialize the react-native app
```javascript
import React from 'react-native';
import fluxibleApp from './app/appFlux';

const {
    AppRegistry
} = React;

const context = fluxibleApp.createContext();
AppRegistry.registerComponent('reactnative', ()=> context.createElement());
```

When I tried to retrive from fluxibleApp.getComponent() the components comes with executeAction, getStorage undefined.

When I tried to retrieve from context.createElement() it is a object and I can't register it.

So, here my question:
How I can intializate the app? 

PS this is my "father" component
```javascript
import React from 'react-native';
import ThemesPage from '../themes/pages/themesPage.jsx';
import provideContext from 'fluxible/addons/provideContext';
import connectToStores from 'fluxible/addons/connectToStores';
import ThemeStore from '../themes/stores/themeStore';

const styles = React.StyleSheet.create({
    container: {
      flex: 1
    }
});

class App extends React.Component{
	constructor(props, context) {
        super(props, context);
        debugger;
    }

	render(){
		return (
				<React.NavigatorIOS
					style={styles.container}
					initialRoute={{
						title: 'Categories',
						component: ThemesPage,
						passProps: this.props
					}}/>
			);
	}
}

App.contextTypes = {
    getStore: React.PropTypes.func,
    executeAction: React.PropTypes.func
};

App = provideContext(App);

App = connectToStores(App, [ThemeStore], (stores)=>{
	return {
		themes: stores.ThemeStore.getThemes()
	};
});
export default App;
```

**Comment by AbrahamAlcaina** [comment]
I did some changes 
```javascript 
import React from 'react-native';
import fluxibleApp from './app/appFlux';

const {
    AppRegistry
} = React;

const context = fluxibleApp.createContext();
const App = fluxibleApp.getComponent();

class QA extends React.Component{
    render(){
        return (
                <App context={context.getComponentContext()} />
            );
    }
}

import provideContext from 'fluxible/addons/provideContext';
QA = provideContext(QA);

AppRegistry.registerComponent('reactnative', ()=> QA);
```

Now the App contains in this.props.context the right getStorage & executeAction (not undefined), 
but nothing in context.
```javascript 
QA = provideContext(QA);
```
Is provideContext right used?

**Comment by bernatmv** [comment]
I'm also having some trouble getting it to work in React Native.

Tried to find some kind of guide explaining the integration with React Native to no avail. Is Fluxible able to work with it?

Thank you

**Comment by mridgway** [comment]
Fluxible will likely not work with react-native right now because of its dependency on `react`. We have a few issues open right now to move all of the dependencies on `react` into a separate `fluxible-addons` package.

**Comment by AbrahamAlcaina** [comment]
thanks @mridgway for you answer.
I'm really interesting in use it, if you need an early adapter/tester, you can count on me.

BTW in my investigation i see that the context is setted right in the constructor, but it is undefined in the render.

**Comment by bernatmv** [comment]
Thank you for your response Michael, will keep an eye on fluxible updates.

Please, let me know if you need any testers for a future fluxible/react-native version.

**Comment by rohit8** [comment]
@mridgway any luck with the separation of dependencies into `fluxible-addons` so this could be used with react-native?

**Comment by redonkulus** [comment]
@rohit8 we have an open PR for this now. It will probably get merged early this week. We have to update fluxible.io first. 

https://github.com/yahoo/fluxible/pull/202

**Comment by AbrahamAlcaina** [comment]
@redonkulus do you have any update? 
It is for the version 1.x.x?

**Comment by redonkulus** [comment]
@AbrahamAlcaina [fluxible@0.5.x](https://www.npmjs.com/package/fluxible) removes the dependency on React (into fluxible-addons-react) so this should be done now. You can test it out with react-native.

**Comment by kilometers** [comment]
Still not working for me. `this.props.context` comes out fine, but `this.context` etc doesn't work. One result is I can't run connectToStores properly.

**Comment by malaman** [comment]
If this is still actual, we've managed to run fluxible app with react-native.
https://github.com/malaman/fluxible-react-native
