### ISSUE TITLE
Routing + Fetch Data architecture

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/fluxible#18]
Howdy,
I am using fluxible-app together with flux-router-plugin and historyWithHash util. Each route is bound to the react component that displays the dynamic data the come from server.
I created the actions that reads the data from server and call the context.disptach once the response is received, for example:
```
var getCustomers =  function(context, payload, done){
            context.dataProvider().read('customers', {}, {}, function (err, customers) {
                context.dispatch('GET_DATA_START');
                if (err) {
                    context.dispatch('ERROR_OCCURED', err);
                }
                else {
                    context.dispatch('RECEIVE_CUSTOMERS', customers);
                }
                context.dispatch('GET_DATA_END');
                done();
            });
}
```
CustomersStore handles the RECEIVE_CUSTOMERS event and emits the changes that intercepted by the Customers component:
```
var CustomersStore = createStore({
    storeName: 'CustomersStore',
    handlers: {
        'RECEIVE_CUSTOMERS' : 'updateCustomersList'
    },
    initialize: function () {
        this.customersList = [];
    },
    updateCustomersList: function (customersList) {
        this.customersList = customersList;
        this.emitChange();
    },
    getState: function () {
        return {
            customersList: this.customersList
        };
    }
});

var CustomersList = React.createClass({
    mixins : [StoreMixin],
    statics: {
        storeListeners: [CustomersStore]
    },
    getInitialState : function() {
        return this.getStore(CustomersStore).getState();
    },
    onChange: function () {
        var state = this.getStore(CustomersStore).getState();
        this.setState(state);
    },
    render : function(){
        var customersTableBody = this.state.customersList.map(function(customer){
            return(
              <tr>
                  <td>{customer.Name.Name}</td>
                  <td>{customer.Company}</td>
              </tr>
            );
        });
        return(
            <table className='table'>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Company</th>
                    </tr>
                </thead>
                <tbody>
                    {customersTableBody}
                </tbody>
            </table>
        );
    }
});

```
Obviously I want to invoke "getCustomers" action when CustomersList component is loaded(when the route is visited), and I am looking for the best way to do that. In addition I plan to intercept GET_DATA_START and GET_DATA_END in order to show/hide the loading indicator.
So far I have several of options:
1. Call getCustomers action in corresponding route's action function
2. Call the same in componentDidMount of CustomersList
3. Call the same in componentWillMount of CustomersList

Do you have any ideas? What would be the best option? Currently I am inclining towards option#3.

**Comment by gpbl** [comment]
@sAbakumoff I liked the idea of putting `done()` before executing the route action. Though, it won't work for server-side rendering: for the client the right place for that would be indeed `componentDidMount`* and `componentWillUpdate`. (*not `componentWillMount` that is called server-side too). 

That infinite loop doesn't sound good: it means your component are being mounted again when the state is updated.

**Comment by gpbl** [comment]
Putting `done` as first thing in the route's `action` property works great on the client, since the user will navigate immediately to the new page and load the content "later". By adding a "LOAD_START" event we would then show a loading message.

Since it does not work for server-side rendering, where I have to wait the store actions to finish, I am using a small function that will run the `done` function immediately on the browser.

I wonder what are other people doing in this case... also, I had to use Promises.

```js
// call done immediately on browser
function wait(promises, done) {
  if (env.BROWSER) done();
  else Promise.all(promises).then(() => { done() });
}

// example route using different store actions
const routes = {
  // route showing a list of books and a list of authors
  books: {
    path: '/',
    action: function(context, payload, done) {
      const books = new Promise((resolve, reject) => {
        context.executeAction(getHomeBooks, {}, resolve);
      });
      const authors = new Promise((resolve, reject) => {
        context.executeAction(getHomeAuthors, {}, resolve);
      });
      wait([books, authors], done);
    }
  },
  // route showing a list of libraries and a list of cities
  libraries: {
    path: '/libraries',
    action: function(context, payload, done) {
      const libraries = new Promise((resolve, reject) => {
        context.executeAction(getLibraries, {}, resolve);
      });
      const cities = new Promise((resolve, reject) => {
        context.executeAction(getCities, {}, resolve);
      });
      wait([libraries, cities], done);
    }
  }
};
```

**Comment by mridgway** [comment]
`done()` is really only relevant on the server-side where we have to make sure we wait before we render the React component. With that said, I think it's best to only call that once your action has fully completed (I/O calls included). If you need to do deferred loads on the client, I agree that `componentDidMount` is the best place to execute a new action. 

If you need optimistic UI updates in your actions, then you can dispatch a `START` event before the I/O call and a `SUCCESS`/`FAILURE` event after it has completed. This way, your store can update its state immediately, and then still react to the output of the response.

**Comment by gpbl** [comment]
Thanks @mridgway for the insights.

> I think it's best to only call that once your action has fully completed (I/O calls included).

However, users have to wait for the actions to finish. Instead, running `done()` immediately provides an instant feedback to the users. Note I talk about the client-side navigation, and in my example above `done` is called after the actions have been launched.

Do you see problems doing this way?

> If you need optimistic UI updates in your actions, then you can dispatch a START event before the I/O call and a SUCCESS/FAILURE event after it has completed.

Definitely. In my code, the action dispatch a `START` event and the store set a `loading: true` state. From what I understand, this happens synchronously when the action is called (no API call yet). 

The component being mounted will get the initial state with `loading: true`. As the action finishes, the store will `emitChange()` and update the component's state.

In this case, I don't see the need of running the action twice, i.e. when `componentDidMount`.

(I'm applying fluxible for a production-candidate app, working great so far.)

**Comment by sAbakumoff** [comment]
btw - here is the full code that shows the approach I am using in the real app:
https://github.com/sAbakumoff/Fluxible-SPA

**Comment by nicolashery** [comment]
Thanks for sharing the code snippet @gpbl, I was looking to do something like this as well (wait for data to load on the server before rendering, but render immediately on the client).

Here is a version that should work with callbacks (vs. promises), using [async](https://github.com/caolan/async). I also tweaked it to show an example of a dynamic route (`/country/:countryId/libraries`).

```javascript
// call `done` immediately on browser, wait for the tasks on the server
function wait(tasks, done) {
  if (env.BROWSER) done();
  else async.parallel(tasks, done);
}

// example route using different store actions
var routes = {
  // route showing a list of books and a list of authors
  books: {
    path: '/books',
    action: function(context, payload, done) {
      var books = context.executeAction.bind(context, getHomeBooks, {});
      var authors = context.executeAction.bind(context, getHomeAuthors, {});
      wait([books, authors], done);
    }
  },
  // route showing a list of libraries and a list of cities for a country
  libraries: {
    path: '/country/:countryId/libraries',
    action: function(context, payload, done) {
      var libraries = context.executeAction.bind(context, getLibrariesForCountry, {
        countryId: payload.params.countryId
      });
      var cities = context.executeAction.bind(context, getCitiesForCountry, {
        countryId: payload.params.countryId
      });
      wait([libraries, cities], done);
    }
  }
};
```

**Comment by gpbl** [comment]
@nicolashery after going on with that idea, I've found it's better skipping *completely* the route actions client-side, and execute those actions `onComponentDidMount` instead. 

The actions may trigger some `*_START` event while the route is not yet changed (e.g. for a `loading` state). I didn't want to call twice the same actions, however it is a better way to keep the data flows inside the components.

So, route actions are relevant only server-side, as @mridgway was suggesting.

Hence your route could just do (note the `return` statement): 

```js
    action: function(context, payload, done) {
      if (env.BROWSER) { 
         done(); 
         return;  // do not execute actions on the browser
      }
      var libraries = context.executeAction.bind(context, getLibrariesForCountry, {
        countryId: payload.params.countryId
      });
      var cities = context.executeAction.bind(context, getCitiesForCountry, {
        countryId: payload.params.countryId
      });
      async.parallel([libraries, cities], done);
    }
```

which is much cleaner. 

Thanks for suggesting `async`. It's much better!

**Comment by nicolashery** [comment]
Thanks @gpbl, I finally got a chance to try this. I like the idea of keeping the data fetching needs inside the component (if you look at Relay/GraphQL it's going in that direction), but I wasn't sure about duplicating it inside the `routes.js` file. So I went with something kind of like this:

```javascript
// routes.js
var routes = {
  libraries: {
    path: '/country/:countryId/libraries',
    views: {
      LeftPanelView: require('./components/Cities.jsx'),
      RIghtPanelView: require('./components/Libraries.jsx')
    },
    action: function(context, route, done) {
      if (env.BROWSER) {
        return done();
      }
      // Grab the `fetchData` static method from each "view" component on `route.config.views`
      // and bind them to context and route
      var dataFetchers = getDataFetchers(context, route);
      async.parallel(dataFetchers, done);
    }
  }
};
```

```javascript
// Libraries.jsx
var Libraries = React.createClass({
  propTypes: {
    context: React.PropTypes.object.isRequired,
    params: React.PropTypes.object.isRequired
  },

  statics: {
    storeListeners: [LibraryStore],

    fetchData: function(context, route, done) {
      context.executeAction(getLibrariesForCountry, {
        countryId: route.params.countryId
      }, done);
    }
  },

  componentDidMount: function() {
    if (this.props.context.isFirstRender()) {
      // On first client render we already have all the data from the rehydration
      // so no need to fetch again
      return;
    }
    ContactMessages.fetchData(this.props.context, {params: this.props.params});
  },

  // ...
});
```

```javascript
// RightPanelView.js
var RightPanelView = React.createClass({
  propTypes: {
    context: React.PropTypes.object.isRequired
  },

  mixins: [StoreMixin],

  render: function() {
    var ViewComponent = this.getStore(ApplicationStore).getView('RightPanelView');
    return React.createElement(ViewComponent, {
      context: this.props.context,
      params: this.getStore(ApplicationStore).getParams()
    });
  }
});
```

The specific commit on the "toy project" where I'm trying this is: https://github.com/nicolashery/example-ismorphic-one/tree/5316cc894a7749cb81127b380129a29fa4bc76c3

At this stage however, I realized that I was sort of reimplementing what [react-router](https://github.com/rackt/react-router) allows you to do. More specifically, get a list of the "handler" components that will be rendered for a specific route, so you can grab their "fetchData" static method (see how they do it in [react-router-mega-demo](https://github.com/rackt/react-router-mega-demo)).

So I ended up switching to `react-router`, which actually plays well with the rest of `fluxible`. Specific commit here: https://github.com/nicolashery/example-ismorphic-one/tree/a599ba55c7c7b47690a9103ad272707cb0aaf035 (there is also an example of using the router here: https://github.com/yahoo/flux-examples/tree/master/react-router).

I'm not sure how this can be applied similarly with `routr`. I guess as long as you can't render a "component tree" with React, you can't walk it to grab some static methods off the components to be rendered...

/cc @redonkulus

**Comment by mridgway** [comment]
This is one of our goals with the flux-router-component is to make it map to a component instead of an action. There's no reason that you couldn't add a component to the route configuration right now and then access statics on it (just like react-router), but we haven't tried out that full user story yet.
