### ISSUE TITLE
MockActionContext is not compatible to ActionContext

### ISSUE THREAD

**Issue by peleteiro** [yahoo/fluxible#184]
It should support actions that returns a Promise.
It should return a promise even if the action is callback based.

**Comment by mridgway** [comment]
I'll take a look at this.

**Comment by peleteiro** [comment]
I can send a pull request with it, but after playing with it I'm not sure if it's worth changing it.

It makes the code much more complex; and it works already if you use actions that way they were written. Ex: If action uses done, test using done; otherwise test using promises.

IMHO

**Comment by mridgway** [comment]
This is true. Making this work would require re-implementing some of the internals of Fluxible's `executeAction`.

If you're fine with it the way it is, then you can close it. If others see this as an issue, then feel free to comment.
