### ISSUE TITLE
TypeScript definition for Fluxible

### ISSUE THREAD

**Issue by igorbt** [yahoo/fluxible#189]
Are there any plans / thoughts on creating and maintaining a TypeScript definition (.d.ts) for Fluxible? It would probably help TypeScript community to use this amazing framework.
BTW, I see that fluxxor has [d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/fluxxor/fluxxor.d.ts)..

**Comment by redonkulus** [comment]
We do not use TypeScript ourselves, so I would be wary that it could get out of date or unmaintained. We would certainly welcome contributions from the community to create the definition file and provide a PR to the DefinitelyTyped project.
