### ISSUE TITLE
Unable to connect to stores

### ISSUE THREAD

**Issue by davidhouweling** [yahoo/fluxible#190]
I've attempted to start a new app with

    yo fluxible

and then in Home.js I wish to add a link to the About page. 

So I attempted to follow http://fluxible.io/api/addons/connectToStores.html

So following along with it... I've tried the following...

```javascript
'use strict';
var React = require('react');
import { NavLink } from 'fluxible-router';
import ApplicationStore from '../stores/ApplicationStore';
import connectToStores from 'fluxible/addons/connectToStores';


class Home extends React.Component {
    render() {
        return (
            <div>
                <h2>Home</h2>
                <p>Welcome to the site!</p>
            </div>
        );
    }
}

Home = connectToStores(Home, [ApplicationStore], function (stores, props) {
    return {
        pages: stores.ApplicationStore.getPages()
    };
});

module.exports = Home;
```

And yes, I know that I am not consuming the props.pages yet, but just trying to wire this up and executing it, on my node console I get...

```console
C:\git\test\node\node_modules\react\lib\ReactDefaultInjection.js:53
    tagName: type.toUpperCase(),
                  ^
TypeError: type.toUpperCase is not a function
    at autoGenerateWrapperClass (C:\git\test\node\node_modules\react\lib\ReactDefaultInjection.j
s:53:19)
    at Object.getComponentClassForElement (C:\git\test\node\node_modules\react\lib\ReactNativeCo
mponent.js:59:49)
    at validatePropTypes (C:\git\test\node\node_modules\react\lib\ReactElementValidator.js:361:45)
    at Object.ReactElementValidator.createElement (C:\git\test\node\node_modules\react\lib\ReactElementValidator.js:408:5)
    at [object Object].render (C:/git\test/node/components/Application.js:20:17)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\git\test\node\node_modules\react\lib\ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\git\test\node\
node_modules\react\lib\ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (C:\git\test\node\node_modules\rea
ct\lib\ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\git\test\node\node_modules\react\lib\ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (C:\git\test\node\node_modules\react\lib\ReactPerf.js:70:21)
```

The exact cause of this is that the import of the store itself (so that it has the type for connectStores to work) causes the error above. But I'm not sure how to solve this. It has stumped me for days.

I did Google around, and saw this blog post... http://ctheu.com/2015/02/26/react-server-side-with-es6-syntax/ but I don't see how it exactly applies as they are referring to sub components and not stores, as well as the fluxible stores already using `export default ApplicationStore;`

Does anyone have any advice as to how I can resolve this?

**Comment by escalona** [comment]
@davidhouweling I've copy and pasted your Home.js into my fresh example and am not seeing the same error. Have you changed any other files?

**Comment by davidhouweling** [comment]
@escalona I've been feeling that my machine has been playing up more and more so I'll format it tonight and attempt to try again and report back.

**Comment by benmonro** [comment]
@davidhouweling  did you ever get this working?  I'm seeing this same error in a very simple hello world.

**Comment by davidhouweling** [comment]
@benmonro sorry I got majorly distracted... only got around to looking into this again. It is still happening the same, however I did manage to work around it.

```js
'use strict';
import React from 'react';
import { NavLink } from 'fluxible-router';
import connectToStores from 'fluxible/addons/connectToStores';

class Home extends React.Component {
    render() {
        return (
            <div>
                <h2>Home</h2>
                <p>Welcome to the site!</p>
                <NavLink routeName={this.props.pages.about.page}>Link to About page</NavLink>
            </div>
        );
    }
}

Home = connectToStores(Home, ['ApplicationStore'], function (stores, props) {
    return {
        pages: stores.ApplicationStore.getPages()
    };
});

module.exports = Home;
```

As you can see, the only real difference is that when you reference the stores, they should be strings instead of the store object itself. These strings should be the `storeName` property of the store you wish to reference.

I guess documentation needs to be adjusted? Though I'd love to hear from the yahoo guys about this.

Just for clarify, i'm on a Windows machine, so this could be the reason you might not see it if you're running in OSX.
