### ISSUE TITLE
 executeAction for `` was called, but `SET_COOKIE` is currently being dispatched

### ISSUE THREAD

**Issue by opportunato** [yahoo/fluxible#194]
Hey!

I am having a warning that goes like this:

executeAction for `` was called, but `SET_COOKIE` is currently being dispatched. This could mean there are cascading updates, which should be avoided. `` will only start after `SET_COOKIE` is complete.

Even though the application still works as supposed, I am still thinking that I am doing something wrong because of probably not understanding fluxible architecture properly. What I am trying to achieve is this.

I want different pages to react differently to the state of user login. So, for example, I want the application to always redirect to the home page after user signing out. I also want for application to redirect to home page after user login, but if the Login was opened via popup, I want no redirect, just a popup close.

The code goes like this (I am using fluxible-router):

```
class LoginPage extends Component {

  static contextTypes = {
    executeAction: PropTypes.func.isRequired
  }

  componentDidUpdate(prevProps) {
    if (!prevProps.isLoggedIn && this.props.isLoggedIn) {
      this.context.executeAction(navigateAction, { url: "/" });
    }
  }

  render() {
    return (
      <Login />
    );
  }
}

LoginPage = connectToStores(LoginPage, ["LocalStore"], (stores) => {
  return {
    isLoggedIn: stores.LocalStore.isLoggedIn()
  };
});
```

The Login component provides the rendering of sign up buttons bind to login actions — so I can use them anywhere. And the action is straightforward:

```
login(context, { auth_token }, done) {
    context.dispatch(Actions.SET_COOKIE, { [Keys.AUTH_TOKEN]: auth_token });
 }
```

And the store handler:

```
onSetCookie(data) {
    _.map(data, (value, key) => {
      this.records[key] = value;
      CookieUtils.writeCookie(key, JSON.stringify(value));
    });
    this.emitChange();
  }
```

Unfortunately, it triggers the warning I provided at the beginning of the page.

I always thought that store emits change only after the dispatching of action was finished — and thought that executing another action from componentDidUpdate would be safe. It looks like I was wrong. So what I am missing? What should my logic be like?

**Comment by ismaelga** [comment]
How did you solve this? I'm having the same warning

**Comment by bamoo456** [comment]
I also got  the same warning. Any suggestion to fix this ?

**Comment by leebenson** [comment]
I had a similar error. In my case, the code to execute the action was as follows:

```
import F from '../utils/fetcher.js';

export default {
    sendMessage(context, payload, done) {

        F.create('message', payload, {}, (e, params) => {
            console.log('data received back=', params);
        });

    }
}
```

The `sendMessage` action was executed on every new page call... so when I navigated to a new route using `navigateAction`, there was a chance that the function was called before the navigation had finished.

I _think_ this is a just a warning for potential race conditions (i.e. firing new actions before the old ones have finished). What fixed this for me was putting this line in:

export default {
    sendMessage(context, payload, done) {

        F.create('message', payload, {}, (e, params) => {
            console.log('data received back=', params);
            done(); // <---- this fixed it
        });

    }
}
```

... because it signals to the dispatcher that the action has finished.

In any case, if you look at yahoo/fluxible/blob/master/lib/FluxibleContext.js#L145 you can see that this warning is only generated when NODE_ENV !== "production", so you shouldn't run into it post-dev.

**Comment by leebenson** [comment]
If the above wasn't clear, you might try:

```
login(context, { auth_token }, done) {
    context.dispatch(Actions.SET_COOKIE, { [Keys.AUTH_TOKEN]: auth_token });
    done(); // <-- add this line
 }
```
