### ISSUE TITLE
An example integrating Fluxible with passport.js

### ISSUE THREAD

**Issue by aefimov64** [yahoo/fluxible#200]
It would be great to populate Fluxible examples with a simple application that manages users with passport and Fluxible to show us how to restrict access to certain parts of our application based on user authentication.

**Comment by ali1k** [comment]
Hi @aefimov64 
I have done it in my application. You can take a look at https://github.com/ali1k/ld-r to see my code which adds authentications as a plugin to Fluxible.

**Comment by aefimov64** [comment]
Thanks @ali1k for your help! Will try to implement your approach in my app.

**Comment by mridgway** [comment]
I don't think we'll add this to our fluxible examples since it's pretty specific. It would be good to add examples of this to http://fluxible.io/community/reference-applications.html though.
