### ISSUE TITLE
connect to stores is throwing this._initializeDispatcher is not a function

### ISSUE THREAD

**Issue by mailaneel** [yahoo/fluxible#203]
```getStore``` is not bound to FluxContext when using ```provideContext```

**Comment by mridgway** [comment]
You should be passing `context.getComponentContext()` to your component when rendering. Like so: https://github.com/yahoo/fluxible/blob/v0.4.x/lib/FluxibleContext.js#L56

**Comment by mailaneel** [comment]
thanks @mridgway that worked. I will close this
