### ISSUE TITLE
Remove dependency on es6-promise

### ISSUE THREAD

**Issue by tleunen** [yahoo/fluxible#205]
Promise are quite supported now across browsers (except IE). Therefore, Fluxible should not have a copy of a Promise shim.

According to [CanIUse](http://caniuse.com/#feat=promises), it's basically just needed for IE.

I suggest to remove it from the code, and add a comment on the website/readme to add a shim for Promice if users need to. That way, it will prevent users from having the same shim multiple times.
I like how Facebook does it with React for example: https://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills

**Comment by mridgway** [comment]
Now that ES2015 has been approved, I tend to agree. I think this will be done with 1.0 release (soon after 0.5).

**Comment by mridgway** [comment]
Resolved in #258
