### ISSUE TITLE
FluxibleContext with fluxible-addons-react

### ISSUE THREAD

**Issue by Ekhoo** [yahoo/fluxible#206]
I use `Fluxible` `v0.4.12` and `Fluxible-addons-react` `v0.1.0`. I would like to use `createElementWithContext` but in line `19` you try to call `fluxibleContext.getComponent()` but in this version of `Fluxible` this method doesn't exist... What can I do ? Will you do a new release ?

**Comment by redonkulus** [comment]
@Ekhoo fluxible 0.4.x does not work with fluxible-addons-react yet, PR #202 will resolve this and we will release 0.5.x alpha release. I'm hoping to get this out today.

**Comment by mridgway** [comment]
0.5.0 was released and is now usable with fluxible-addons-react.
