### ISSUE TITLE
feature:  when using connectToStores, add a way to signal that component should not update

### ISSUE THREAD

**Issue by mailaneel** [yahoo/fluxible#207]
Example: 

When listening to RouteStore, if we want to wait for navigation to finish successfully before updating.

```js 

class Comments extends Component{}

connectToStores(Comments, [RouteStore], function(context){
   if(!context.getStore(RouteStore).isNavigateComplete()){
    // if we want to wait for navigation complete before sending data
     return false;
   }
}) 

```
or when listening to multiple stores 

```js
connectToStores(Comments, [UsersStore, CommetsStore], function(context){
   if(context.getStore(UserStore).isEmpty() || context.getStore(CommentsStore).isEmpty()){
    // this happens when one store triggers change event before the other one
     return false;
   }
}) 
```
The way i am doing currently is by returning

```js
return {
 isLoading: true
} 
```

**Comment by cesarandreu** [comment]
One approach worth considering is making a higher order component, react-router 1.0.0 has an experimental folder with [AsyncProps](https://github.com/rackt/react-router/blob/master/modules/experimental/AsyncProps.js) which it looks promising.

**Comment by mailaneel** [comment]
makes sense

when ```async``` or ```wait``` is passed as third argument similar to below

```js 
// sample async
function async(asyncOptionalProps) {

    asyncOptionalProps = asyncOptionalProps || {}
    asyncOptionalProps.isAsync = true;

    //this refers to wrapped connectToStores component
    this.setState({asyncProps: asyncOptionalProps})

   // Instead of returning done, we can wait for promise to resolve as well?? 
    return function done(err, asyncResolvedProps) {
        // this refers to wrapped connectToStores component
       //  we can also have a way of passing asyncErrorProps
        this.setState({asyncProps: null, newProps: asyncResolvedProps})
    }

}
```

```js
connectToStores(Comments, [UsersStore, CommetsStore], function(context, props, async){
   someThingAsync(async({loading: true}))
}); 
```

**Comment by mailaneel** [comment]
In some cases where we have frequently changing stores, would be nice to wait for previous async to finish before calling ```stateGetter``` again

**Comment by mridgway** [comment]
It looks like if you return `null` from the stateGetter it will not update the state already, but will unfortunately cause a warning from React's `setState`. I'm open to adding a `null` check before calling `setState`.

I'm not a big fan of adding asynchrony to the `connectToStores` API as it may cause race conditions and complexity.

**Comment by mailaneel** [comment]
It is working for me with out async currently. In my case actions are taking care of all async and updating stores. 

+1 for return null / false to cancel update

@mridgway could you please share your inputs on how you are handling loading state for components.

**Comment by mridgway** [comment]
@mridgway For page level you can use the `isNavigateComplete` prop to determine whether to render the full page or a page level loading interface. For component level, you should have your store set a loading flag based on the action `START` and `SUCCESS/ERROR` dispatches. That way the component that listens to that store can choose what to render based on that loading flag.

**Comment by mailaneel** [comment]
thanks @mridgway

**Comment by mailaneel** [comment]
After using this for some time now, I do not see any use of returning null
In my case connectToStores is only called when data required for page is loaded(using route action)

Example:
```js
var routes = {
   comments: {
    path: '/comments',
    action: function(){
      return Promise.all([loadComments(), loadUser()])
    }
   } 
}
```

as suggested by @mridgway components can check ```isNavigateComplete``` to show loading state
