### ISSUE TITLE
FluxibleMixin 0.5

### ISSUE THREAD

**Issue by lohek** [yahoo/fluxible#218]
Hi !

I just updated my project with fluxible but... I have a problem with FluxibleMixin
`Warning: Failed Context Types: Required context executeAction was not specified in Body.`

I think the problem is that :
Before : https://github.com/yahoo/fluxible/blob/989cc2ca7aa2b75eb34e28acc5a844b43f17c3d4/mixins/FluxibleMixin.js#L42-L43
After : https://github.com/yahoo/fluxible-addons-react/blob/master/FluxibleMixin.js#L43-L44

**Comment by mridgway** [comment]
Does the mixin still work or is it failing entirely? It seems like your context is not being set correctly which causes this to warn correctly (it didn't before because it wasn't considered required by React).

**Comment by lohek** [comment]
It works, but I just have a lot of warnings.
I go through a iFrame with this kind of `FluxibleComponent` to properly spend the context:
```
'use strict';

var React = require('react/addons');

/**
 * FluxibleComponent doing its job right.
 */
var MounterContextTunnelComponent = React.createClass({
    displayName: 'MounterContextTunnelComponent',
    propTypes: {
      context: React.PropTypes.object.isRequired
    },

    childContextTypes: {
      executeAction: React.PropTypes.func.isRequired,
      messages: React.PropTypes.object.isRequired,
      locales: React.PropTypes.string.isRequired,
      getStore: React.PropTypes.func.isRequired
    },

    /**
     * Provides the ***FULL*** current context as a child context
     * @method getChildContext
     */
    getChildContext: function () {
      return {
        getStore: this.props.context.getStore,
        executeAction: this.props.context.executeAction,
        messages: this.props.context.messages,
        locales: this.props.context.locales
      }
    },

    render: function () {
      return React.addons.cloneWithProps(this.props.children, {
          context: this.props.context
      });
    }
});

module.exports = MounterContextTunnelComponent;
```

And if I change the ` contextTypes` of `FluxibleMixin` by the old code, I have no more warnings.

**Comment by mridgway** [comment]
Did you end up figuring out what the issue was here? The FluxibleMixin does require those methods to be available, so it's strange that it would warn but still work.
