### ISSUE TITLE
Better example of testing

### ISSUE THREAD

**Issue by mmahalwy** [yahoo/fluxible#221]
Hi guys,

The current testing docs is really confusing and I have stitched my own way which worked for a while but quickly reached it's limits. See:

```
import {createMockComponentContext} from 'fluxible/utils';

import React from 'react';
import ReactTestUtils from 'react/lib/ReactTestUtils';
import Audioplayer from 'components/audioplayer/Audioplayer';
import provideContext from 'fluxible/addons/provideContext';
import SurahsStore from 'stores/SurahsStore';
import AyahsStore from 'stores/AyahsStore';
import AudioplayerStore from 'stores/AudioplayerStore';

import getSurahs from '../../../fixtures/getSurahs';
import getAyahs from '../../../fixtures/getAyahs';

let component, node, makeComponent, context;

describe('Audioplayer', function() {
  beforeEach(function() {
    context = createMockComponentContext({
      stores: [AudioplayerStore, SurahsStore, AyahsStore]
    });

    context.getStore('SurahsStore').surahs = getSurahs;
    context.getStore('AyahsStore').ayahs = getAyahs;
    context.getStore('AudioplayerStore').currentAyah = getAyahs[0];
    context.getStore('AudioplayerStore').currentAudio = new Audio;

    var AudioplayerClass = provideContext(Audioplayer);

    component = ReactTestUtils.renderIntoDocument(
      <AudioplayerClass context={context}  />
    );

    console.log(AudioplayerClass, component);

    node = React.findDOMNode(component);
  });

  it('should render', function() {
    expect(node).to.exist;
  });
```

Now, I'd like to write a test to determine the state of my `Audioplayer` component, but I cannot, given that `component` is actually the `provideContext` component... If I remove the `provideContext` karma errors out saying `this.context.getStore` is undefined...

**Comment by Vijar** [comment]
@mmahalwy would your use case be solved by doing something like this: `node = React.findDOMNode(component.refs.wrappedElement);` ?

**Comment by maconley** [comment]
I've been working on this for a while and I think I have something fairly solid. I'll apply your example with some of what I've done, hopefully it's helpful.

````
describe('Audioplayer', function() {
  beforeEach(function() {
    let testStores = [AudioplayerStore, SurahsStore, AyahsStore];
    let context = createMockComponentContext({
        stores: testStores
    });
    let testComponent = provideContext(connectToStores(component, testStores, function() {
        return {/*props for component go here*/};
    });
    let component = TestUtils.renderIntoDocument(<testComponent context={context} />);
    component = TestUtils.findRenderedComponentWithType(component, Audioplayer);
  });
````

You don't have to [dig around](https://gitter.im/yahoo/fluxible/archives/2015/05/20) or use refs, you simply have to find the rendered `Audioplayer` component within the `provideContext` wrapper using React `TestUtils`.

I actually have not needed that last line to test the original component so far, as my tests have been more focused on what was rendered and firing actions, but you will need it if you want to test the state/props.

You can factor most of that out to a helper function to cut down on copy and pasting as well.
