### ISSUE TITLE
Stubbing methods on components wrapped in provideContext or connectToStores

### ISSUE THREAD

**Issue by mmahalwy** [yahoo/fluxible#222]
When a component is wrapped with `provideContext` or `connectToStore`, it returns a whole new component. How do I stub methods on the original wrapped component? In other works, how do I access the wrapped component's methods and state? 

Thanks

**Comment by mmahalwy** [comment]
My current solution has been:
```
foundComponent = ReactTestUtils.findAllInRenderedTree(component, function(t) {
      t.constructor.name === 'Audioplayer';
});

sinon.stub(foundComponent, 'someMethod');
```

This looks terrible. I tried:
```
ReactTestUtils.findRenderedDOMComponentWithClass(component, 'audioplayer')
```
but with no luck did it actually retrieve the component...

**Comment by gpbl** [comment]
How would it work exporting also the component itself?

```js
export class MyComponent extends React.component {
   // render() etc
}
export default connectToStores(MyComponent, ["MyStore"], /* .etc.. * /);
```

then in your tests:

```js
import { MyComponent } from "./MyComponent"
```

However I see the issue for testing using high order components. An alternative that has been suggested is to apply them on import side. IE leave your component "pure":

```js
export default MyComponent extends React.component {
   // render() etc
}
```

and apply the wrapper after the import:

```js
import { connectToStores } from "fluxible-addons-react";
import MyComponent from "./MyComponent"

MyComponent = connectToStores(MyComponent, , /* .etc.. * /);
```

**Comment by mmahalwy** [comment]
@gpbl the importing, although fixes the problem, it's very clean and DRY. I have some components that are imported in many places, and that'd mean I'd have to create the connectToStores everywhere.

My so far, and I am happy with it solution although the code looks ugly, is the `findAllInRenderedTree`
If only react had a `findAllInRenderedTreeByConstructor` that'd be amazing.

**Comment by gpbl** [comment]
And what about exporting both the components? The pure one (that you will test) and the wrapped one? 

(if you are using so many times the same wrapped components, I'd reconsider a bit the architecture - i.e wrap only the top level components in the UI hierarchy, then pass props.)

**Comment by mmahalwy** [comment]
I thought of having two exports too. That may work, but I haven't tried it really. But it _might_ work.

**Comment by peterKaleta** [comment]
Do you guys have any way of accessing refs of rendered component?
Currently I have : 

```
import Loader from '../loader.jsx';

{...}

beforeEach(function() {
  context = createMockComponentContext();
  Loader = provideContext(Loader);
});

{...}

  it('shows preloader and not children when processing', function () {

    wrappedLoader = TestUtils.renderIntoDocument(
      <Loader context={context} processing={true}/>
    );

{...}
```

**Comment by ghislaindj** [comment]
Getting the same issue here : I've got a LeftNav component with a toggle function and a connectToStore (in order to fill the LeftNav). When I put the connect to store, impossible to access the toggle function ...

**Comment by mmahalwy** [comment]
@ghislaindj you can explore what i did here: https://github.com/quran/quran.com-frontend/tree/master/tests/client
