### ISSUE TITLE
Ways to disable debug loggin?

### ISSUE THREAD

**Issue by yhjor1212** [yahoo/fluxible#224]
I am now modifying my login console logging in the browser and wonder if there are any ways I can disable debug logging as sensitive information like password will be exposed in the console.

As I check inside the code, I found the following code but it does not have debug checking enabled:
debug('Executing action ' + displayName + ' with payload', payload);

Any ways that can enable me to do so? Thanks a lot!

**Comment by mridgway** [comment]
In your client.js file you can do the following:

```js
import debug from 'debug';
debug.disable();
```

See https://github.com/visionmedia/debug#browser-support for more information about how to use the debug library.

**Comment by mridgway** [comment]
Closing this. If you have any issues related to this you can reopen.
