### ISSUE TITLE
Actions without error handlers swallow errors

### ISSUE THREAD

**Issue by rahatarmanahmed** [yahoo/fluxible#227]
Using fluxible 0.5.1, running in Electron (though I don't think that should matter).
```javascript
let app = new Fluxible({});

let action = function(context, payload, done) {
    console.log('before throw');
    throw new Error('I get swallowed');
    console.log('after throw');
}

let context = app.createContext();
context.executeAction(action, {})
// Console only outputs "before throw"
```

There's no indication that an action had an error if you don't specify a done function or don't catch with .catch(), the error just gets swallowed.

My issue happens in an action context, but this example has the same issue. I've tried giving Fluxible a `componentActionHandler` but it doesn't get called, probably because the action didn't come from a component context.

**Comment by mridgway** [comment]
While weird, I'm not sure how we can avoid this while still supporting promises. Ideally you should pass a callback to `executeAction` or catch errors on the promise returned from `executeAction` where you can handle errors that occur in your application flow.

If this is also occurring in the component context, we will need to ensure that the `componentActionHandler` is called.
