### ISSUE TITLE
add a way to automatically register stores and services for a component

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#232]
I was just wondering if you got any plan to automatically register stores and services for a component. For example, now you have 'fluxible-router' component which brings a Route store but you still need to register it manually in the application. I think it would be great if we could manage to automatically register the stores and services which come by components.

**Comment by mridgway** [comment]
This would require static analysis of the code (probably at build time). It would be interesting for sure though. Perhaps babel would be of use here. 

With that said, I don't think this would be built in to Fluxible, more of a helper in a separate package.

**Comment by ali1k** [comment]
@mridgway fair enough!  For my use case, I found it very important because I wanted to allow a  distributed (unfixed and non-deterministic) set of components to be plugged into the fluxible system on the fly. I will work on it and will let you know if I could handle it!
