### ISSUE TITLE
New in 0.5.x 

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/fluxible#234]
Hi guys,
I decided to move my app to es6 syntax and started to review the fluxible samples and noticed very interesting code at https://github.com/yahoo/flux-examples/blob/master/react-router/components/Application.js:
```javascript
@provideContext
class Application extends React.Component {
...
}
export default Application;
```
similar code can be found in https://github.com/yahoo/flux-examples/blob/master/react-router/components/Page.js
it starts with
```javascript
@connectToStores([PageStore], (context) => context.getStore(PageStore).getState())
```
I am not sure why provideContext and connectToStores calls start with "@"? 
Could you please explain? I can see that these lines were introduced within "Upgrade to Fluxible@0.5.x" changeset, so it seems to be something new in 0.5.x?
Also, I am currently using fluxible version ^0.4.0, which basically means 0.4.12
Could you explain what are the new features of version 0.5.x in general?

**Comment by gpbl** [comment]
@sAbakumoff there's a [change log](https://github.com/yahoo/fluxible/blob/master/CHANGELOG.md) :-) The `@` is because they are used as decorators, read about them [here](http://cocktailjs.github.io/blog/traits-with-es7-decorators.html).

**Comment by redonkulus** [comment]
thanks @gpbl. we document it here http://fluxible.io/addons/connectToStores.html#decorator

**Comment by sAbakumoff** [comment]
Okay, can you explain why these lines:
```javascript
static contextTypes = {
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func
    };
```
were added in https://github.com/yahoo/flux-examples/blob/master/react-router/components/Application.js
?
As far as I can tell the code works without them, right?

**Comment by mridgway** [comment]
https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html has a good run down of the undocumented context usage. The component must define a static `contextTypes` in order to access the corresponding key son the context. Think of it as an opt-in for receiving the specified context values.
