### ISSUE TITLE
React-router and connectToStores

### ISSUE THREAD

**Issue by bringking** [yahoo/fluxible#235]
Writing a basic component that uses react-router and fluxible, it seems that the ```willTransitionTo``` static method stops working if you use the  connectToStores decorator. Any ideas why this might be the case?

```
@pageTitle("Insights Admin: Home")
@requiresAuth
@connectToStores([AuthStore], ( context, props ) => ({
    AuthStore: context.getStore(AuthStore).getState()
}))
class Home extends React.Component {

    static willTransitionTo( transition, params, query ) {
        console.log('transitioning to home')
    }

    static contextTypes = {
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func
    };

    render() {
        return (<div>Home {this.props.AuthStore.loggedIn.toString()}</div>);
    }
}

export default Home;
```

**Comment by mridgway** [comment]
`connectToStores` will create a wrapping component and hoist the static methods to the parent. You may need to make sure that your decorators are doing the same. We use [`hoist-non-react-statics`](https://github.com/mridgway/hoist-non-react-statics) for this.

**Comment by bringking** [comment]
Ah it seems to be an issue with loose mode-

```
class test{
  static willTransitionTo(test,yup){
    
  }
}
console.log(Object.keys(test));
```

Drop this into https://babeljs.io/repl/ and toggle loose mode on and off, with loose mode off, Object.keys doesn't enumerate because babel marks them not enumerable when they define the property

**Comment by bringking** [comment]
Here is the where it is failing in non-loose mode-

https://github.com/mridgway/hoist-non-react-statics/blob/master/index.js#L19

**Comment by bringking** [comment]
Also, I was able to fix my code by doing the following- 

```
@connectToStores([AuthStore], ( context, props ) => ({
    AuthStore: context.getStore(AuthStore).getState()
}))
@pageTitle("Insights Admin: Home")
@requiresAuth
class Home extends React.Component {

    static contextTypes = {
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func
    };

    render() {
        return (<div>Home </div>);
    }
}
Home.willTransitionTo = function( transition, params, query ) {
    console.log("transitioning to home");
};
export default Home;
```

So not sure if this is a bug, or just a result of using ES7 class properties, but good to track the issue here.

**Comment by mridgway** [comment]
Yeah, we should definitely keep an eye on whether ES7 class properties will be enumerable. I would imagine they won't be, which will cause this hoisting to break down. We may need to find a better solution.
