### ISSUE TITLE
Hoist non-static methods with connectToStores does not work

### ISSUE THREAD

**Issue by Anomen** [yahoo/fluxible#236]
Hi everyone!

I'm having troubles accessing my methods after using connectToStores on a class. It seems that connectToStores just detroys my methods.

Here is my code:
```javascript
class SelectCategoryCmp extends React.Component {
    constructor(params) {
        super(params);

        // Bind "this" to the methods.
        this.getValue = this.getValue.bind(this);
    }

    getValue() {
        return this.refs.select.getValue();
    }

    componentWillMount() {
        this.context.executeAction(CategoryActions.fetch);
    }

    componentWillUnMount() {
        this.context.executeAction(CategoryActions.fetch);
    }

    render() {
        var categories = this.props.categories || [];

        return (
            <Select ref='select' title={i18n.t('select_category')} options={categories} />
        );
    }
}

// Here, SelectCategoryCmp.prototype.getValue() DOES exist.

SelectCategoryCmp = connectToStores(SelectCategoryCmp, [CategoriesStore], (context) => ({
    categories: context.getStore(CategoriesStore).getCategories()
}));

// Here, SelectCategoryCmp.prototype.getValue() does NOT exist anymore.
```

I'm compiling this ES6 code with babel, and I'm using the latest version of React and Fluxible.

Thanks!
Kev

**Comment by tleunen** [comment]
`connectToStores` wraps your component inside another component so that's why you can't access the function. Because it doesn't exist in the resulted component.

I don't think it's a good thing to access data from a component with getter functions. You should use a callback function prop to get the data when the component changes.

**Comment by mridgway** [comment]
The `getValue` method in your example is an instance method, not a static method. You are correct, you won't be able to access the instance method directly since there is a component that wraps it. @tleunen's recommendation to pass callbacks down to children is a good idea.
