### ISSUE TITLE
Using same components multiple times

### ISSUE THREAD

**Issue by olegman** [yahoo/fluxible#239]
I have some problems when using same component multiple times on a same page. For example, I have ```<Carousel />``` component, which I want to use twice on a page, but with different state. For now I handle this by creating uniq identifiers for each component and adding them to the single store in hash map like this:
 ```{ <id>: <state>, <anotherId>: <anotherState> }```
But it seems to be a bad idea, because every change to the store will render all ```<Carousel />``` components. Maybe someone knows better solution to the problem?

**Comment by cesarandreu** [comment]
That's what [shouldComponentUpdate](http://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate) is for.

You could use something like [immutable.js](http://facebook.github.io/immutable-js/) with something like [react-immutable-render-mixin](https://github.com/jurassix/react-immutable-render-mixin).

**Comment by koulmomo** [comment]
:+1: to what @cesarandreu said. 

The other option is to move the `state` to the `<Carousel />` (or a wrapper) component itself.
