### ISSUE TITLE
Testing actions that call services 

### ISSUE THREAD

**Issue by amirrajan** [yahoo/fluxible#247]
Hey guys and gals, I'm looking at the following documentation: http://fluxible.io/api/actions.html

The action I'm attempting to test has a call to a service endpoint. Here is a snippet:

```
export function requestSomethingFromService(actionContext, payload, done) {
    actionContext.service.get('people', null, payload, (err, result) => {
```

Using the following test yields a null reference exception (stating that the `service.get` is null):

```
    beforeEach(function () {
        actionContext = createMockActionContext({
            stores: [SomeStore]
        });
    });

    it('works', done => {
        requestSomethingFromService(actionContext, { }, function () {
            done();
        });
    });
```

Is the `.service` property not wired up for a `mockActionContext`? How can I test an action that invokes a service?

**Comment by mridgway** [comment]
In this case I think you should just mock out the `service.read` by adding your own mock object on to `actionContext`:

```js
var readCalls = [];
actionContext.service = {
    read: () => {
        readCalls.push(arguments);
        return mockData;
    }
}
```

This would allow you to test that the service was called with the correct arguments without actually calling a service.

If you wanted to do integration testing, you could call the fluxible-plugin-fetchr's [`plugActionContext` method](https://github.com/yahoo/fluxible-plugin-fetchr/blob/master/lib/fetchr-plugin.js#L89), but this might get a little hairy and you would want to make sure you aren't doing actual I/O from your service by mocking out the requests.

**Comment by amirrajan** [comment]
I'll give that a shot and see how deep the rabbit hole goes.

**Comment by amirrajan** [comment]
Just to help the next person that may be interested in doing something like this:

```
import fetchrPlugin from 'fluxible-plugin-fetchr';

        actionContext = createMockActionContext({
            stores: [SomeStore]
        });

        var service = fetchrPlugin({
            xhrPath: '/api'
        });

        service.registerService(SomeService);

        service.plugContext({
            xhrContext: { },
            req: { ip: '127.0.0.1',
                   cookies: { },
                   headers: {
                       'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
                       'accept-language': 'en-US,en;q=0.8',
                       'Content-Type': 'application/json'
                   }
                 }
        }).plugActionContext(actionContext);

```

You can pass in `actionContext` to whichever action you wish.
