### ISSUE TITLE
Webpack Setup Question re: setImmediate 

### ISSUE THREAD

**Issue by localnerve** [yahoo/fluxible#250]
Fluxible uses YuzuJS setImmediate for action execution and promise resolution.

However, by default, webpack uses [node-libs-browser](https://github.com/webpack/node-libs-browser), which installs [an alternative setImmediate](https://github.com/jryans/timers-browserify) that ends up being setTimeout based - **The alternative version ends up getting called by Fluxible.**
This is really not-so-good for UI actions.

This also happens in the [Yahoo flux-examples](https://github.com/yahoo/flux-examples) that I build.

I would be super grateful is someone could share some workarounds for this, or point out the proper/preferred way to setup webpack to make sure Fluxible YuzuJS setImmediate wins out.

Any help much appreciated.

**Comment by mridgway** [comment]
Perhaps we can open an issue on https://github.com/jryans/timers-browserify to see if they can use YuzuJS's implementation or on https://github.com/defunctzombie/node-process to have a more robust fallback for `nextTick`.

I'm not sure how to hook into Webpack's polyfills.

**Comment by localnerve** [comment]
I found a solution. Add:
```javascript
node: {
  setImmediate: false
}
```
To your [webpack config](http://webpack.github.io/docs/configuration.html#node). timers-browserify is then removed from the bundle output, and the YuzuJS impl intended by Fluxible gets used instead.

My initial tests show this is a 60fps winner on modern browsers. :trophy: 

:shirt: ?

**Comment by mridgway** [comment]
Great find! We're going to update the scaffolding to include this.

**Comment by localnerve** [comment]
I'm satisfied with this solution. (Closing)
