### ISSUE TITLE
Unable to get context from the onclick event

### ISSUE THREAD

**Issue by scotthuang** [yahoo/fluxible#253]
I want to bind a click event just like the actions example.

http://fluxible.io/api/actions.html

So i do it like this:

    function testAction(actionContext, payload, done) {
        setTimeout(function () { // simulate async
            actionContext.dispatch('MY_ACTION', payload);
            done();
        }, 10);
    }

    class Home extends React.Component {
	static contextTypes = {
            executeAction: React.PropTypes.func.isRequired,
            getStore: React.PropTypes.func.isRequired
        }

        onClick() {
    	    console.log(this)
    	    this.context.executeAction(testAction, {});
        }

        render() {
    	    var list = this.context.getStore(TestStore).getTestData()

    	    var listHtml = list.map(function(i){
    		    return <div>{i}</div>
    	    })

            return (
                <div>
                    <h2>Home</h2>
                    <p>Welcome to the site!</p>
                    <div>{listHtml}</div>
                    <button onClick={this.onClick}>click me</button>
                </div>
            );
         }
 
    }

But it doesn't work because the variable 'this' is undefined. Ather searching on stackoverflow, i figure it out by the following code:

    <button onClick={this.onClick.bind(this)}>click me</button>

Does the doc has something wrong ? 
Do I get the wrong way to use component ?

**Comment by gpbl** [comment]
Yes, `this.onClick.bind(this)` is the right way. [Send a pull request](https://github.com/yahoo/fluxible/tree/master/docs/api/Actions.md) :-)

**Comment by koulmomo** [comment]
yep. This is a consequence of moving to the ES6 `class` syntax. 

[`React.createClass` magically autobinds methods for you](https://github.com/facebook/react/blob/master/docs/_posts/2015-01-27-react-v0.13.0-beta-1.md#autobinding)
