### ISSUE TITLE
Delete store content if no longer needed

### ISSUE THREAD

**Issue by tindli** [yahoo/fluxible#27]
Lets say there is a page with a /products link that populates a product store with a ton of data.

If someone then clicks on a link to a totally unrelated content e.g. "/about" one would
possibly like to reset/delete the content of the product-store to reduce the memory pressure.

So what is the appropriate way to delete store entries in an automated way?

One way I can think of is to allow a store to delete its content as
soon as the last listener is detached... this should be configurable
but disabled as a default I think.

How do you handle store data that is not required anymore?

**Comment by mridgway** [comment]
I think it would be up to the store to listen for an event that it would use for clearing its data. It could be a higher level page change event or an explicit "cleanup" event that could be fired via the `componentWillUnmount` component lifecycle event.

**Comment by tindli** [comment]
Hmmm ok sounds somewhat reasonable.

Nevertheless I guess using "componentWillUnmount" could be dangerous because this component 
has to be sure, that there is no other component that currently renders stuff 
based on this data (somewhere else on a page)...

So the store would need to know at least if there is an active listener at the time it receives the 
cleanup event. If yes, the cleanup event should be ignored....
I don't know if its currently possible for a store to get the number of active listeners...

**Comment by mridgway** [comment]
A store could call `this.listeners('change')` to get back a list of the event handlers: http://nodejs.org/api/events.html#events_emitter_listeners_event

**Comment by tindli** [comment]
wow that was fast - thanks!
OK I think an appropriate solution can be built based on this steps.

**Comment by mridgway** [comment]
Cool. We haven't played around with this too much, so let us know how it goes!

**Comment by tindli** [comment]
yeah I will... thanks again!
