### ISSUE TITLE
How to execute action in a service?

### ISSUE THREAD

**Issue by scotthuang** [yahoo/fluxible#271]
I want to validate some params in both client side and server side. So before executing "update action", I want to execute "validate action" first.

The logic looks like this:

client side:

    button click -> validateAction(api getXxx) -> if(validate == true) updateAction(api UpdateXxx. Server side also fires a validate action) -> store -> view

server side:

    api UpdateXxx -> validateAction(api getXxx) -> if(validate == true) update db -> store -> view

In the client side, it works. But there is no "context" variable in server side. So how to get a "context" in service. 

If it cannot do it, how to validate some params in client and server properly?

client side code:

	onClick() {
		let rtx = jQuery('#rtx-name').val();
		let me = this;

		me.context.executeAction(validateRtxName, {rtx: rtx}, function(validateResult){
			//validate fail
		    if(validateResult.rtn != 0){
		        alert(validateResult.msg);
		        return false;
		    }

		    me.context.executeAction(loadColleague, {rtx: rtx});
		});
    }

server side code:

    update: function(req, resource, params, body, config, callback) {
        /*
            validate input
            How can I get the "context"???
         */
        this.context.executeAction(validateRtxName, params, function(validateResult){
            //validate fail
            if(validateResult.rtn != 0){
                callback(null, validateResult);
                return false;
            }

            //get real data
            oainfoCli.getStaffInfo([defaultUser], function(oainfoData){
                //do something
                callback(null, oainfoData);
            });
        }) 
    }

**Comment by Vijar** [comment]
@scotthuang Calling validate action before calling update on your service, will ensure that your params are always validated by the time they get to the service.

But sometimes redundancy is necessary. So I would recommend that your validation logic be broken out into a separate util that is used directly by the service as well as the validate action.

Also since validate and update seem so tightly coupled, I would think about combining them into one action so you can ensure params are validate before being passed into the service call.

**Comment by scotthuang** [comment]
I have figured it out by making a distinction between server side and client side in the validate action.

The action is triggered when it can get the context and then dispatch another action to assess service. On the server side, I can't get data by service(context.service.read) itself because it can't get a context. I have to get data directly through a http request.

    export default function validateRtxName(context, payload, done) {
        let defaultUser = typeof payload['rtx'] != 'undefined' ? payload['rtx'] : '';
        let failResult = {
            rtn: 1,
            msg: 'something wrong'
        };
        let rtxRe = new RegExp(/^[a-z]{0,10}$/);
        let rtxFlag = true;

        //check params
        if(defaultUser != ''){
            failResult['msg'] = 'rtx format is not correct';
            rtxFlag = rtxRe.test(defaultUser);
        }

        if(typeof context == 'undefined'){
            // server side get data by custom function
            if(!rtxFlag){
                //static check format
                done(failResult);
            }else{
                oainfoCli.getStaffInfo([defaultUser], function(oainfoData){
                    if(oainfoData.rtn == 0){
                        if(oainfoData.data.length == 0){
                            debug('rtx: ' + defaultUser +' is not existed')
                            failResult['msg'] = 'rtx is not existed';
                            done(failResult);
                        }else{
                            done(oainfoData);
                        }
                    }else{
                        failResult['msg'] = 'oainfo service error';
                        done(failResult);
                    }                
                });
            }
        }else{
            // client side get data by read service 
            if(!rtxFlag){
                //static check format
                context.dispatch('UPDATE_COLLEAGUES_FAIL', []);
                alert(failResult.msg)
                done();
            }else{
                context.service.read('colleague', payload, {}, function (err, userInfo) {
                    if(userInfo.rtn == 0 && userInfo.data.length != 0){
                        context.executeAction(loadColleague, {rtx: defaultUser});
                    }else{
                        context.dispatch('UPDATE_COLLEAGUES_FAIL', []);
                        failResult['msg'] = 'rtx is not existed';
                        alert(failResult.msg)
                    }

                    done();
                })
            }
        }
    }

button click:

	onClick() {
		let rtx = jQuery('#rtx-name').val();
		let me = this;

		me.context.executeAction(validateRtxName, {rtx: rtx})
    }

service:

    update: function(req, resource, params, body, config, callback) {
        // Get oainfo singleton
        let oainfoCli = new Oainfo();

        let defaultUser = typeof params['rtx'] != 'undefined' ? params['rtx'] : '';
        let groupId = 0;
        let groupName = '';

        //validate input
        validateRtxName(undefined, params, function(validateResult){
            //validate fail
            if(validateResult.rtn != 0){
                callback(null, validateResult);
                return false;
            }

            //get real data
            oainfoCli.getStaffInfo([defaultUser], function(oainfoData){
                if(oainfoData.rtn == 0 && oainfoData.data.length != 0){
                    oainfoCli.getStaffsByGroupId([groupId], function(colleagueData){
                        callback(null, colleagueData);
                    });
                }
            });
        }) 
    }

It is too diffcult to validate by the same code in both client side and server side...

**Comment by mridgway** [comment]
It wouldn't be possible to call an action from a service since services could be called from the browser. Ideally you would abstract out this validation to a separate library that could be required by both the service and the client-side store.

I have thought about whether posts should be treated as Flux actions before, but I don't think it would make sense unless the store was able to make service calls itself so that stores could be the central place that does that validation. This is not on our roadmap right now though.
