### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#273]
I'm considering whether we should move many of the official packages under the same git repo rather than having them spread out across the Yahoo org. As an example, you can see [Babel's explanation](https://github.com/babel/babel/blob/development/doc/design/monorepo.md) of why they prefer a single repo for multiple packages rather than many.

I tend to agree, especially when we are doing upgrades for React versions, it can be a pain to coordinate multiple repos rather than being able to do everything at once as part of one repo.

Here is a list of what we (the Fluxible team) currently maintain:

Fluxible specific (more likely to have common repo)
* [x] `fluxible` (#274)
* [x] `fluxible-reducer-store` (#275)
* [x] `generator-fluxible`
* [x] `fluxible.io`
* [x] `flux-examples`
* [x] `fluxible-addons-react`
* [x] `fluxible-router`
* [x] `fluxible-plugin-fetchr`
* [x] `dispatchr`

Standalone (more likely to stay independent)
* `routr` (_internal to fluxible-router but used by others like redux-universal-router_)
* `hoist-non-react-statics` (_generic_)
* `fetchr` (_generic_)

**Comment by cesarandreu** [comment]
+1

Managing lots of repos is hard, if moving it into a single repo helps you iterate on things it sounds like a big win.

**Comment by mdressman** [comment]
+1

no more `npm link` madness

**Comment by pablolmiranda** [comment]
:+1:

**Comment by akshayp** [comment]
:100: A long but good read on the topic from twitter's experience with bringing things into a monorepo http://www.gigamonkeys.com/flowers/

**Comment by redonkulus** [comment]
:+1: would make our lives easier for sure. Like the idea of having the docs and website in one repo, will make fluxible.io easier to parse the docs too.

**Comment by mridgway** [comment]
I'm leaning towards moving `dispatchr` in since it's a core piece of Fluxible. It would still remain uncoupled.

**Comment by redonkulus** [comment]
> I'm leaning towards moving dispatchr in since it's a core piece of Fluxible. It would still remain uncoupled.

:+1:

**Comment by localnerve** [comment]
This is cool, but always reminds me "this is more of a Shelbyville idea".

**Comment by mridgway** [comment]
It is done. There may still be some links that are broken, so if you see any 404s please let us know.
