### ISSUE TITLE
0.5.5 is tagged as the latest release instead of 1.0.0

### ISSUE THREAD

**Issue by growlsworth** [yahoo/fluxible#277]
Hey fluxible,

For some reason 0.5.5 is marked as the latest release instead of 1.0.0. Demonstrated here: https://www.npmjs.com/package/fluxible . It seems that 1.0.0 is the most up to date version.

Thanks!

**Comment by mridgway** [comment]
Oops, you're right. Fixed. Thanks for letting us know.
