### ISSUE TITLE
Update Documentation to include render using fluxible-addons-react/createElementWithContext

### ISSUE THREAD

**Issue by pablolmiranda** [yahoo/fluxible#278]
The createElement is not more present on the `FluxibleContext` interface. This make the documentation  present at `http://fluxible.io/guides/bringing-flux-to-the-server.html#introducing-the-fluxible-library-a-href-https-github-com-mridgway-flux-example-tree-master-chat-full-example-a-` outdated.

**Comment by mridgway** [comment]
So this "guide" we are considering a blog post. It is too much work to update it for every release of Fluxible and React. It was more of an introduction on how to get Flux to work on the server, but I think that is well understood now.
