### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by pablolmiranda** [yahoo/fluxible#290]
On the __Stores__ page:
![screen shot 2015-10-23 at 2 05 49 pm 3](https://cloud.githubusercontent.com/assets/27819/10704967/5b266f60-798f-11e5-994d-400da93816e6.png)

**Comment by mridgway** [comment]
Looks like the caches for docs expired and the new documentation structure is causing breakages. I will push the latest version of the site to fix this.

**Comment by mridgway** [comment]
Latest version has been deployed. Can you check again and see if you're still getting the error?

**Comment by pablolmiranda** [comment]
Thanks for the update. Everything is working fine.

On Friday, October 23, 2015, Michael Ridgway <notifications@github.com>
wrote:

> Latest version has been deployed. Can you check again and see if you're
> still getting the error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yahoo/fluxible/issues/290#issuecomment-150717569>.
>


-- 
Att,

Pablo Lacerda de Miranda
pablolmiranda@gmail.com
+1 408 685 1578
