### ISSUE TITLE
Uncaught TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by Anomen** [yahoo/fluxible#291]
Hi everyone,

When I install the 1.0.0-rc1 version of fluxible, I get a `Uncaught TypeError: Object.assign is not a function`. In the prior version, I noticed that `object-assign` was imported in the project, wich is not the case for the latest version.

Thanks!
Kev

**Comment by Vijar** [comment]
@Anomen This was done on purpose. We recommend you polyfill `Object.assign`.

We're starting to do this for all of our repos. See https://github.com/yahoo/fluxible-router/pull/93#issuecomment-149288132

**Comment by operatino** [comment]
Making dependencies require special app configuration with some polyfills is really bad. It's like forcing all the consumers to use specific environment and build tools. 

And it 100% will cause a LOT of problems for big amount of developers, especially if you update dep, test in chrome and then get errors in browsers like IE totally unexpected.

And reason for making it lighter is really not valid, `object-assing` dep weights nothing https://github.com/sindresorhus/object-assign/blob/master/index.js.

**Comment by localnerve** [comment]
Can't disagree more. Devs should be made aware of all their polyfills,
sooner the better.

**Comment by operatino** [comment]
`object-assign` is not a polyfill, it's a small library. It doesn't extend the Object, it provides a function that does merging. You don't call Lodash a polyfill right?
