### ISSUE TITLE
Update to v1.0.0 

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/fluxible#292]
Hi,
I can see that v1.0.0 has been released, but I didn't find any CHANGELOG or migration guidelines. Could you please share them?

**Comment by mridgway** [comment]
You can find them here:

 * [Changelog](https://github.com/yahoo/fluxible/blob/master/packages/fluxible/CHANGELOG.md#100)
 * [Upgrade](https://github.com/yahoo/fluxible/blob/master/packages/fluxible/UPGRADE.md#100)
