### ISSUE TITLE
Consider adding the transaction ID to MockActionContext

### ISSUE THREAD

**Issue by gpbl** [yahoo/fluxible#296]
Hi, I'd like to test a [use case](https://github.com/yahoo/fluxible-router/pull/95) where I use `context.rootId` inside an action. I expect I can write something something like

```js
mockContext = createMockActionContext({ stores: [...] });
console.log(mockContext.rootId); // print a uuid
```

I'd send a PR to change [MockActionContext](https://github.com/yahoo/fluxible/blob/a1dd75ebf2e76456ad2ec903e77104cc70b9ec44/packages/fluxible/utils/MockActionContext.js):

```js
// same function from FluxibleContext.js
var GLOBAL_UUID_MAX = Math.pow(2, 53);
function generateUUID () {
    return Math.ceil(Math.random() * GLOBAL_UUID_MAX);
}
function MockActionContext (dispatcherContext) {
    this.dispatcherContext = dispatcherContext;
    this.executeActionCalls = [];
    this.dispatchCalls = [];
    this.rootId = generateUUID(); 
}
```

... but if right shouldn't we before export that `generateUUID()` somewhere? 

Thanks!

**Comment by mridgway** [comment]
:+1: Yes that method can be extracted out to `lib/generateUUID.js`.

**Comment by koulmomo** [comment]
@mridgway any reason you're not using an external lib to manage `uuid` generation? I was thinking https://www.npmjs.com/package/uuid

or are you thinking it's overkill for this use case?

**Comment by gpbl** [comment]
@koulmomo imho npm's `uuid` does toooo much :)
