### ISSUE TITLE
Object.assign

### ISSUE THREAD

**Issue by jeron-diovis** [yahoo/fluxible#299]
https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/connectToStores.js#L12
Does anybody care about `Object.assign` support? Old browsers, old Node?
Just upgraded this package to latest version, and everything crashed due exactly to this, is it normal?

**Comment by kaesonho** [comment]
Hi @jeron-diovis, we will recommend you to polyfill `Object.assign`, 
more detail please see the discussion on #291 and https://github.com/yahoo/fluxible-router/pull/93#issuecomment-149288132
