### ISSUE TITLE
Client Only Actions - Stream to Server

### ISSUE THREAD

**Issue by kobelb** [yahoo/fluxible#30]
I just began using the fluxible project, and I'm very impressed. Prior to this project, I created my own flux framework; however, it wasn't isomorphic, and I'm very impressed with the way this project works isomorphically.

However, I've come across a situation where I want to allow the user to record some audio using the new HTML5 audio capabilities, and obviously this is something that should only be triggered client-side. My initial thoughts were to create an action that is only invoked client-side; however, something feels dirty regarding this approach.

Do you have any suggestions for handing this differently?

**Comment by gpbl** [comment]
I don't see anything wrong calling actions only client-side. Just make sure you stay out from the server, i.e. subscribe the events triggering the client-only actions in `componentDidMount`.

**Comment by mridgway** [comment]
:+1: to what @gpbl said. Client-side only actions are totally fine.

**Comment by kobelb** [comment]
Awesome. Thanks guys!
