### ISSUE TITLE
[generator] Upgrade to Babel 6

### ISSUE THREAD

**Issue by tleunen** [yahoo/fluxible#300]
Any plan to upgrade to babel 6 ?

**Comment by mridgway** [comment]
Yes. I haven't had time to look in to the upgrade, but if you want to send a PR that would be great.

**Comment by raelmiu** [comment]
+1

**Comment by lowsky** [comment]
Doesn't it already work with babel6? 
Did anybody run into problems?
Until fully supported, are there workarounds? Thx!

**Comment by mridgway** [comment]
Yeah, there should be no issues with Fluxible and babel 6. I will rename this ticket to reflect that we should upgrade the generator.
