### ISSUE TITLE
Document the proper way to install `generator-fluxible` with `npm@3.x.x`

### ISSUE THREAD

**Issue by throoze** [yahoo/fluxible#302]
I had a hard time trying to install `generator-fluxible` with the following environment:

```
throoze@keter:~/dev/fluxible$ npm -v
3.3.12
throoze@keter:~/dev/fluxible$ node -v
v5.0.0
throoze@keter:~/dev/fluxible$ yo --version
1.5.0
throoze@keter:~/dev/fluxible$ sudo npm install -g generator-fluxible
/usr/local/lib
├── generator-fluxible@1.2.0 
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-fluxible@1.2.0 requires a peer of yo@>=1.0.0 but none was installed.
```

After googling for some time, I saw an issue open in other generator about the same error. They commented it was due to the version of the `npm` (3.x.x). After I downgraded to `npm@2.14.9`, I could finally install `generator-fluxible`, but the following warning was thrown:

```
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-fluxible will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

this makes me think there is a proper way to make it work with npm 3+. I looked for it but I couldn't find it in any official doc. It would help a lot if documentation about it was included in the official Docs site.

Thanks!

**Comment by redonkulus** [comment]
@throoze I believe the issue is that `yo` is only a devDependency. In npm@2 it would be installed automatically, but in npm@3, it will not be installed for you. I can fix the package and publish a new version.

**Comment by redonkulus** [comment]
turns out this is incorrect, since its a global package, you will need to install `yo` globally yourself. This is mentioned in the readme: https://github.com/yahoo/fluxible/tree/master/packages/generator-fluxible#getting-started

**Comment by throoze** [comment]
Hi! thanks for your quick response. I do have `yo` globally installed. That's the unexpected behavior. I'm working on Ubuntu 14.04 LTS.

**Comment by redonkulus** [comment]
I'm testing this on my mac 10.10, works fine with npm3 after yo is installed globally.

**Comment by tannerjfco** [comment]
I'm encountering the same reported error with node v5.0.0, npm 3.4.1, yo 1.4.7. generator-fluxible will not install due to dependency error:
> ├── generator-fluxible@1.2.3
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-fluxible@1.2.3 requires a peer of yo@>=1.0.0 but none was installed.

**Comment by tannerjfco** [comment]
I've resolved my issue - in my case yo was linked to a different version and location than what npm was installing globally to. I determined this with ```which yo```.  I suggest doing this and seeing if the path matches other global packages like npm. My case was likely due to replacing nvm with n.
