### ISSUE TITLE
fluxible almost taking a second to rehydrate

### ISSUE THREAD

**Issue by mmahalwy** [yahoo/fluxible#305]
Hey guys, 

It almost takes 1s (700ms exactly) to rehydrate my stores where I feel like if I did it in vanilla JS it would be faster. Thoughts on how to make it faster?

Thanks!

**Comment by mridgway** [comment]
I'm curious what you mean by doing it in vanilla JS. 

The rehydrate code handles plugin and store rehydration. Plugins rehydration can be asynchronous, so you could check to see if one of the plugins you're using is doing something async.

The store rehydration is pretty straightforward: https://github.com/yahoo/dispatchr/blob/master/lib/DispatcherContext.js#L125.

One other thing to look at is whether the rehydrate is taking the most time or the parsing/execution of the dehydrated data is taking up the most time.

**Comment by redonkulus** [comment]
fyi @mmahalwy

**Comment by mmahalwy** [comment]
Going to close this - i am going to dig into why this is happening, perhaps my stores dehydrated are too large.
