### ISSUE TITLE
websocket polling is happening even in the production server

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#307]
I do not quite understand it but when I use the production environment, my app is still polling the webpack-dev-server. I tried the fluxible generator default config and in the production env it tries to do http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1447341762302-0

is there any config in webpack to disable this polling in the production server?

update: as I see the issue is that the value of process.env.NODE_ENV in webpack.config.production.js is not sent to the server.js file!

**Comment by mridgway** [comment]
Ah, I see. We are not explicitly setting NODE_ENV, but it's common practice on heroku or any other serving stack to set the NODE_ENV=production. The webpack config does not affect what happens on the server.

**Comment by ali1k** [comment]
yes, I added NODE_ENV=production explicitly to the npm build script and the issue is resolved!
