### ISSUE TITLE
1.0.2 is missing index.js

### ISSUE THREAD

**Issue by micahroberson** [yahoo/fluxible#309]
Looks like a publishing glitch

**Comment by mridgway** [comment]
Looking into and fixing now.

**Comment by mridgway** [comment]
Looks like a bug in `npm`. Updating to latest fixed the issue. Publishing a 1.0.3.

Thanks for bringing this to my attention @micahroberson!

**Comment by mridgway** [comment]
v1.0.3 has been published. Sorry for the inconvenience.

**Comment by micahroberson** [comment]
Thanks for the quick fix!
