### ISSUE TITLE
Fluxible version 0.5.6, Object.assign

### ISSUE THREAD

**Issue by Bazze** [yahoo/fluxible#311]
Hello!

I had `fluxible` version `^0.5.2` specified in my `package.json` which gave me version `0.5.6` when I finally got to it to update some packages today. I can't seem to find the tag here in the git repo (?), but it seems to include your decision on clearing out `object-assign` and relying on the `Object.assign` function instead which we all know is not supported natively in all browsers yet (and I don't have a polyfill in place which covers third party packages, I noticed).

So, if my findings are correct I think we can conclude that this change is not a backwards compatible fix which should reside under the PATCH version of semver. 

Could you bring some clarity on this? I'm staying on `0.5.5` for now, since it still makes use of the `object-assign` lib.

Thanks.

**Comment by mridgway** [comment]
You're right, an `Object.assign` call slipped in while backporting a commit for the 0.5.x branch. I will fix and release new version.

**Comment by mridgway** [comment]
Should be fixed in `fluxible@0.5.7`.

**Comment by Bazze** [comment]
Wow, thanks for fixing it so quick. Clumsy of me to not look closer at the code though, as you say, it was only on one place and not the whole concept I talked about. Thank you!
