### ISSUE TITLE
Error: Cannot find module 'fluxible-addons-react/createStore'

### ISSUE THREAD

**Issue by jeromecovington** [yahoo/fluxible#312]
http://fluxible.io/addons/createStore.html

I see an example for `'fluxible-addons-react/createStore'` but when I try to require this path, I unfortunately am getting an error in the console.
```
Error: Cannot find module 'fluxible-addons-react/createStore'
```

Should I be able to require this module, or is it meant only to be imported via the ES2015 module style?

**Comment by mridgway** [comment]
Looks like a typo. Should be `require('fluxible/addons/createStore');`. I'll fix this now.

**Comment by jeromecovington** [comment]
@mridgway Ok great. Thanks! (Confirmed that the dependency works with the path in your comment, above.)
