### ISSUE TITLE
context.createElement is not a function in fluxible 1.0.x

### ISSUE THREAD

**Issue by jeromecovington** [yahoo/fluxible#314]
Upgraded the app from fluxible v0.4.x to v1.0.x and all is looking well, except that this error is now happening. `context.createElement is not a function`

The relevant lines of code seem to be:
```
// ...
var app = new Fluxible({
    component: Application
});
// ...
var context = app.createContext();
// ...
React.renderToString(context.createElement());
```
It seems that `createElement` has been moved to [`fluxible-addons-react`](https://github.com/yahoo/fluxible/blob/cee85d0fa25b50634ae0ade00e916bfd65fa49a1/packages/fluxible-addons-react/createElementWithContext.js) but how should we now initialize our app instance with this in mind?

**Comment by mridgway** [comment]
The [`createElementWithContext(context, props);`](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/docs/api/createElementWithContext.md) has replaced `context.createElement(props)`. This was to decouple Fluxible core from React.

**Comment by jeromecovington** [comment]
@mridgway Thanks!
