### ISSUE TITLE
Fluxible Generator Firefox Mutating Prototype Warning

### ISSUE THREAD

**Issue by bondydaa** [yahoo/fluxible#318]
I used the [Fluxible Yeoman Generator](https://github.com/yahoo/fluxible/tree/master/packages/generator-fluxible) to create a simple project and upon installation and firing up localhost:300 (not adding any custom code) in Firefox (version 42.0) the following warning was output in the dev console:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create main.js line 2135 > eval:17:415`

I couldn't fine any issues previously reported here but did find some other issues [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/issues/550) and [react-router](https://github.com/rackt/react-router/issues/1155) which lead me to think it might have something to do with compiling ES6 code to ES5 but that is just a guess.

**Comment by ntotten** [comment]
I am seeing this same issue

**Comment by mridgway** [comment]
Looks like it may be part of babel's polyfill which is core-js: https://github.com/zloirock/core-js/issues/46

**Comment by bondydaa** [comment]
Thanks Michael, I assumed babel was most likely the reason that was being thrown.

**Comment by mridgway** [comment]
It doesn't seem like there's anything that we can do on our end to fix this.
