### ISSUE TITLE
Fluxible-addons-react Object.assign dependency not removed

### ISSUE THREAD

**Issue by nhsiehgit** [yahoo/fluxible#321]
Saw in the changelogs of fluxible-addons-react that dependency on Object.assign had been removed

However I'm still seeing it here https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/connectToStores.js#L12

Am I missing something?

**Comment by nhsiehgit** [comment]
Oh wait. I guess you mean we have to include an Object.assign polyfill ourselves.

ok nvm closing

**Comment by thomasjshafer** [comment]
I do not use the babel-loader for my node_modules directory. Is it possible that fluxible could export a version that does not a special loader. Thanks.

**Comment by andrewmunro** [comment]
+1. I don't want to have to transpile all my node_modules.
