### ISSUE TITLE
fluxible-addons-react@0.2.1 seems to be missing provideContext.js

### ISSUE THREAD

**Issue by brev** [yahoo/fluxible#323]
The new `fluxible-addons-react@0.2.1` seems to be physically missing the `provideContext.js` file. It shows back up if I downgrade back to `@0.2.0`. Weird right? thanks.

**Comment by mridgway** [comment]
Weird. This is the second time something like this has happened during a release. I'll look into it. For now I have unpublished 0.2.1.

**Comment by mridgway** [comment]
Still not sure how that happened. 0.2.2 was released and our internal test suite passed with this version. Let me know if you're seeing issues with this release.

Thanks @brev for the quick notification of the issue.
