### ISSUE TITLE
client specific javascript (jquery plugins, etc.)

### ISSUE THREAD

**Issue by travelio** [yahoo/fluxible#33]
Hi,

how do you handle javascript, that should only run on the client?
E.g. a jQuery plugin, that has a dependency on the scroll position.

It doesn't make any sense to render this on the client (and raises an other problem, requiring bower components in node).

How do you guys handle that?

Best,
Sebastian

**Comment by koulmomo** [comment]
@sebslomski there are two ways you can have client only code not get executed on the node server.

1. if you are using an external npm module that behaves differently on the server + client, use the [browser](https://gist.github.com/defunctzombie/4339901) field in the `package.json`. This is what [fetchr](https://github.com/yahoo/fetchr/blob/8609b4f2bae151029b98779141c5ef3de4c31d5a/package.json#L6) and [superagent](https://github.com/visionmedia/superagent/blob/ccd01eeaab12ca48dc2fb81a126f6802f2ff81ac/package.json#L47) do.

2. wrap your client only code in a `typeof window !== ‘undefined’` and make sure to only call the action that uses it in the [componentDidMount](http://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount) lifecycle method

**Comment by airato** [comment]
I use something like this with webpack
```js
if ( process.browser ) {
  // do stuff
}
```
I don't know though is it right or not, but it works for me. I use it for GA and FB api initialization for example

**Comment by redonkulus** [comment]
Agree with @koulmomo, you would need to do some environment check to ensure it doesn't run on the server. Or leverage the browser field as mentioned.
