### ISSUE TITLE
[router] NavLink should detect whether to follow link automatically

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible#337]
See https://github.com/yahoo/fluxible-router/issues/44

**Comment by hfter789** [comment]
@mridgway Is this done? I am seeing that the followLink prop https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js#L109 is doing the job.

**Comment by mridgway** [comment]
This feature would automatically check if the route is registered and follow the link if it is not.

**Comment by mridgway** [comment]
Added in #396
