### ISSUE TITLE
question: managing UI state in a fluxible implementation

### ISSUE THREAD

**Issue by geekyme** [yahoo/fluxible#34]
Hello, I want to seek your advice on managing UI state in a flux architecture / fluxible app. 

From my understanding, there are 3 kinds of state: 

1. Router state - This is handled pretty well by React-router, mapping components to different urls. 

2. Persistent state - Getting a list of documents, etc. Fluxible stores and fetchr work well to populate and sync persistent state between the browser and server. 

3. UI state - Things like opening and closing a modal. 

After reading http://www.thomasboyt.com/2014/09/15/no-fit-state.html, I am curious how do we fit (3) in the context of a flux architecture where actions are designed to be fire-and-forget ? 

Perhaps we have a use case like this: 

1. User hits a 'Create' button, it opens up a modal for user to fill in some data.
2. After filling in the data and hitting submit, a loading icon appears and the submit button is disabled / muted. 
3. On error, the loading icon disappears, the submit button is enabled, and error messages are being displayed in the modal form (still open).
4. On success, the loading icon disappears, the form is cleared, and a success message is being displayed in the modal form, which will close itself in 3 seconds and redirect to another page.

In a traditional web app using jquery or some other MVC framework, we will simply rely on ajax calls made by a view and listen to its callback to alter UI state. However this doesn't appear very uni-directional unlike in a flux implementation. 

But in a flux implementation, how do we do this? 

Do we move UI state into flux stores ? Or do we do something else? 

Thanks :)

**Comment by redonkulus** [comment]
Typically, we would fire an optimistic update to display the UI as if the XHR succeeded or show a loading screen while the XHR call is in progress. You can see an example of the events being fired [in our ToDo example](https://github.com/yahoo/flux-examples/blob/master/todo/actions/updateTodo.js). The `UPDATE_TODO_START` triggers the store callback, which can modify the store state and notify the component.

**Comment by geekyme** [comment]
In other words… moving UI state into the store?

**Comment by redonkulus** [comment]
Yes, you would have an application store or something similar that could manage the state.

**Comment by mohammedpithapurwalasc** [comment]
This seems like a terrible way to handle UI state. May be a better approach is to have UI listen for these events directly in the dispatcher ?

**Comment by koulmomo** [comment]
@mohammedpithapurwalasc The recommended flux architecture is to have your components subscribe to Store's change event. Ideally your components should never interact with the dispatcher.

see https://medium.com/brigade-engineering/what-is-the-flux-application-architecture-b57ebca85b9e for an overview of Flux

**Comment by cesarandreu** [comment]
I keep all state in stores. If it's something ephemeral (e.g. it doesn't affect anything else) I'll wrap my controller component with an automated one.

**Comment by bjrmatos** [comment]
@cesarandreu could you show me an example of that? gist?
