### ISSUE TITLE
[router] Auth & Redirect

### ISSUE THREAD

**Issue by adam-26** [yahoo/fluxible#347]
Hi, I'm having trouble understanding the correct flow to use in regards to determining if a request is (or is not) authenticated, and how to redirect the request if required.

If I use an action on this example route:
```javascript
protectedResource: {
    path: '/protected',
    method: 'get',
    handler: require('../components/Protected'),
    action: function (context, payload, done) {
        // use store to determine if user is authenticated
        var isAuthenticated = false;
        if (!isAuthenticated) {
            context.executeAction(navigateAction, { url: '/login' }, done);
            return;
        }
        
        done();
    }
}
```

The request is redirected, but the browser history is incorrect. I assume this is because the original navigate action can not be cancelled, or is this a bug? Is there a way to redirect an 'in-progress' navigateAction?

I need this logic to execute on both the client and the server (so I can not use a components `componentDidMount()` method as this does not render on the server). Not to mention that loading a component for the sole purpose of redirection seems unnecessary.

This seems like a simple/common use case for a router, if I were using react-router I would use the route 'onEntry' or a components 'static willTransitionTo' functionality to achieve the desired behavior. 

Please advise, Thanks. 
Adam.

**Comment by raphaelparent** [comment]
Hello @adam-26, how did you manage to make that work?

I'm currently struggling with that kind of 'protected data' flow. I have a SessionStore, which has informations like the connected user and I want to verify that user before every route change.

**Comment by mccarter** [comment]
wondering the same thing.....
