### ISSUE TITLE
Please update the babel-eslint package in yeoman generator

### ISSUE THREAD

**Issue by djbk** [yahoo/fluxible#352]
https://github.com/yahoo/fluxible/blob/master/packages/generator-fluxible/app/templates/package.json

I've been getting an error due to the current version of `babel-eslint` via `npm run lint`. Updating it to at least `4.1.6` worked for me (including `5.0.0 beta`). Thanks!

**Comment by mridgway** [comment]
Thank you. I reproduced this. I will get this fixed and released immediately.
