### ISSUE TITLE
Please clarify interface of fluxible store

### ISSUE THREAD

**Issue by c089** [yahoo/fluxible#355]
I am a bit confused by the documentation of stores:

For a `Store` it is "recommended to extend an event emitter so that your store can emit change events to the components". This is also what the examples for writing your own store do, and how [BaseStore](https://github.com/yahoo/fluxible/blob/master/packages/dispatchr/addons/BaseStore.js) and [createReducerStore](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-reducer-store/docs/api/createReducerStore.md) (indirectly by reusing [createStore](https://github.com/yahoo/fluxible/blob/master/packages/dispatchr/addons/createStore.js)) are implemented. But then `connectToStore` uses `addChangeListener` on the store, which in turn does nothing but delegate to `on('change')`. Yet that just seems to be copied from the [Flux docs](https://facebook.github.io/flux/docs/overview.html#structure-and-data-flow) which also say: 

> The stores then emit a _change_ event to alert the controller-views that a change to the data layer has occurred.

So what is fluxible store API now? `store.AddChangeListener` or `store.on('change'`)? At the moment both work, but I would like to make sure I'm using the API right.

**Comment by mridgway** [comment]
`store.addChangeListener()` is a convenience method added by BaseStore and createStore. This follows the same API that Flux actually used: https://github.com/facebook/flux/blob/e0a52d0dada7b78e7197026dc8cf35d84991f0e8/examples/flux-chat/js/stores/UnreadThreadStore.js#L32

These utilities are not required to use Fluxible: you can implement your own stores without extending Fluxible's as basic classes. The [documentation on Stores](http://fluxible.io/api/stores.html) documents the required API for building your own classes and the [`BaseStore` docs](http://fluxible.io/addons/BaseStore.html#built-in-methods) talk about the methods that are added on top of the required store API.

I think we could clarify this in the docs better. If you have any ideas on how to do that please let me know.

**Comment by mridgway** [comment]
> But then connectToStore uses addChangeListener on the store, which in turn does nothing but delegate to on('change').

We should probably change this to use `on('change', listener')` instead so that it works with stores that don't extend `BaseStore`. I will create a separate issue to track this.

**Comment by mridgway** [comment]
Created https://github.com/yahoo/fluxible/issues/356 as a followup for connectToStores. 

This issue can be used for documentation changes that are needed.

**Comment by c089** [comment]
> I think we could clarify this in the docs better. If you have any ideas on how to do that please let me know.

So I see two main issues currently. The formulation "_recommended_ to extend an event emitter" (emphasis by me) and that the fact that emitting changes is only documented in the examples. So I would add something like this:

```md
## Notifying of changes and subscribing to Store

A fluxible store must implement the `EventEmitter` interface and use it to `.emit('change')` whenever the store contents change. Clients can subscribe to updates to the store by adding a listener using `on('change', handler)`.
```

**Comment by mridgway** [comment]
That looks good to me. Want to PR a change to the doc?

**Comment by c089** [comment]
I do, but I'm very busy this week. I'll put it on my todo list but no promise there ;)

**Comment by redonkulus** [comment]
Thanks for the PR!
