### ISSUE TITLE
[fluxible-plugin-fetchr] Document xhrTimeout option 

### ISSUE THREAD

**Issue by jenswegar** [yahoo/fluxible#366]
Fetcher has an option to modify the xhrTimeout, but this plugin does not provide a way to configure that option it seems. Code would be

app.plug(fetchrPlugin({
    xhrPath: '/api', // Path for XHR to be served from
    xhrTimeout: 2000 // timeout for xhr requests
}));

**Comment by mridgway** [comment]
This should be allowed already: https://github.com/yahoo/fluxible/blob/master/packages/fluxible-plugin-fetchr/lib/fetchr-plugin.js#L28. Looks like it's just not documented.

**Comment by jenswegar** [comment]
Yes indeed, code supports it but documentation does not mention the support.
