### ISSUE TITLE
Documentation for `type` property of `navigateAction`

### ISSUE THREAD

**Issue by DullReferenceException** [yahoo/fluxible#370]
We had to dig through `NavLink`code to find this, but `navigateAction` takes a `type` property in the action payload, and a value of `replacestate` will enable the `replaceState` functionality of the `History` api.

It seems like this ought to be documented here:

https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/docs/api/navigateAction.md

**Comment by redonkulus** [comment]
@DullReferenceException thanks for the pointer. I've added in https://github.com/yahoo/fluxible/commit/b2788bb486ac6b418e86e4cab1a0a5081517aefe

Thanks!
