### ISSUE TITLE
do not assign ref to stateless function components

### ISSUE THREAD

**Issue by pwmckenna** [yahoo/fluxible#377]
On React 0.14 I get the following warning when using `connectToStores` on a stateless function component:
 
```
Warning: Stateless function components cannot be given refs (See ref "wrappedElement" in StatelessComponent created by StoreConnector). Attempts to access this ref will fail.
```
when doing something like

```js
connectToStores(() => <div>Hello World</div>, [Store], context => ({}));
```

because you can't specify a ref for a stateless component.See the note at the bottom of  https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

# Suggested Fix:

Use a check like this:
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isClassComponent.js

to conditionally pass in the ref here:
https://github.com/yahoo/fluxible/blob/master/packages/fluxible-addons-react/connectToStores.js#L56

**Comment by mridgway** [comment]
https://github.com/facebook/react/issues/4936 for more context.

If this check is reliable, :+1: on adding it to all HoCs.

**Comment by pwmckenna** [comment]
I'm happy to put together but I immediately was stumped by the choice of where to get the `isComponentClass` function.

- shared utility in fluxible...not sure how to do this given that multiple repos need it (fluxible, fluxible-router, etc)
- require recompose
- pull isComponentClass into its own repo, publish, then have each repo require it.
- inline the function where needed.

Take your pick and I'll implement :)

**Comment by mridgway** [comment]
I looked into whether React has its own function for checking this, but it seems they just inline it: https://github.com/facebook/react/blob/bbd5a78efaf92b7ffcde2a1923112b8931855209/src/renderers/shared/reconciler/ReactCompositeComponent.js#L164 for the best performance. I think we can just use the same logic since HoC's always require a `Component` to be passed in anyway.

**Comment by pwmckenna** [comment]
sounds good, i'll make a PR
