### ISSUE TITLE
Enable debug

### ISSUE THREAD

**Issue by Diokuz** [yahoo/fluxible#382]
How to set to `true` this field?

https://github.com/yahoo/fluxible/blob/efff55f584617e420d8507d15b189569af631321/packages/fluxible/lib/FluxibleContext.js#L117

**Comment by redonkulus** [comment]
@diokuz that's just using the debug module syntax. You can enable in the browser with:

```js
debug.enable('Fluxible:*');
```

Or on the server with:

```js
DEBUG=Fluxible:* node server.js
```

**Comment by localnerve** [comment]
In the browser, you can also enable in local storage.

**Comment by redonkulus** [comment]
@localnerve do you have an example?

**Comment by localnerve** [comment]
Sure.

You can do this on any app compiled with debug intact (debug-ability vs. size = well-worth-it), as is the case in the prod build of [flux-react-example](https://github.com/localnerve/flux-react-example).

1. Chrome, goto http://flux-react-example.herokuapp.com
2. Start DevTools, Goto Resource tab
3. Expand Local Storage, select `http://flux-react-example.herokuapp.com`
4. Add a key `debug`, add value `*`
5. Reload page - debug output appears in console.
