### ISSUE TITLE
[fluxible-router] The actions of rehydrated routes fails

### ISSUE THREAD

**Issue by qatsi** [yahoo/fluxible#388]
Hi! Have some issues with the actions of routes added using `'RECEIVE_ROUTES'`.

With static routes, added with `withStaticRoutes(..)`, they are added in app.js both on server and client side and the RouteStore doesnt dehydrate these. As a result the routes actions are always executed in the correct context and all the module dependancies within main.js (created with webpack) are resolved correctly.

However, we also add some dynamic routes by dispatching the `'RECEIVE_ROUTES'` on server side. These are then dehydrated and rehydrated into the client side app. The problem we are facing is that the routes work fine server side, but on client side the route actions are executed in the incorrect context, since they are executed within the `<script>` tag where they were dehydrated. As a result they cannot resolve any of the required dependancies.

Should this be considered a bug in fluxible-router? Are we doing something wrong or is there some reasonable workaround?

**Comment by qatsi** [comment]
Some example code
```javascript
// dynamicRoutes.js
var loadPage = require('../actions/pages/loadPage');
let dynamicRoutes = {
    hello: {
        path: '/se/hello',
        method: 'get',
        action: loadPage
    }
};
```
```javascript
// loadPage.js
var fetchSomeData = require('./../data/fetchSomeData');
module.exports = function loadPage(context, payload, done) {
    context.executeAction(fetchSomeData, {}, function () {
        done();
    });
};
```
After doing `context.dispatch('RECEIVE_ROUTES', dynamicRoutes);` on server side, the following will be dehydrated

```html
<script>
window.App = {
    //...
        "RouteStore": {
            //...
            "routes": {
                "hello": {
                    "path": "\u002Fse\u002Fhello",
                    "method": "get",
                    "action": function loadPage(context, payload, done) {
                        context.executeAction(fetchSomeData, {}, function () {
                            done();
                        });
                    }
                }
            }
        }
    //...
};
</script>
```

Then when navigating to this route on the client side a `Uncaught ReferenceError: fetchSomeDate is not defined` is recieved

**Comment by mridgway** [comment]
The typical method of requiring your action in the routes will not work when they are dynamic because the action is not serializable. You will have to map the action to a string and then have some way of mapping the string to a require'd action.

fluxible-router already supports calling a `context.loadAction(actionName)` to look for a string-mapped action, but you would need to create a context plugin that implements that method.

**Comment by qatsi** [comment]
Aha, I see [navigateAction.js](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/navigateAction.js) has that logic, to call `context.getAction(actionName)` if the route action is a string. So I guess we just need to implement the method, which takes a string and returns the appropriate action, like in [this example](https://github.com/yahoo/fluxible/blob/master/packages/fluxible/docs/api/Plugins.md) and it should work as expected. Will look into it, tnx!

**Comment by localnerve** [comment]
In case it helps, [flux-react-example](https://github.com/localnerve/flux-react-example) uses dynamic routes from [data](https://github.com/localnerve/flux-react-example-data/blob/master/resources.json) via a [route store](https://github.com/localnerve/flux-react-example/blob/master/stores/RouteStore.js) and a [transformation](https://github.com/localnerve/flux-react-example/blob/master/utils/FluxibleRouteTransformer.js).
