### ISSUE TITLE
Plugin componentContext is not getting pass down into the component

### ISSUE THREAD

**Issue by trungpham** [yahoo/fluxible#39]
https://github.com/yahoo/fluxible/blob/26a5353cec5f3776f12305fc8a1eb0c10f7ef579/mixins/FluxibleMixin.js#L41

Need to account for plugin component context. otherwise they will get dropped by React.

**Comment by Vijar** [comment]
At first glance, I'm not sure if this is possible because contextTypes is a static property, and the plugin component context is dynamic based on what plugins you choose to use in your app.

I'm going to look into this more though.

**Comment by Vijar** [comment]
@trungpham After talking about this issue with the team, I don't think this is possible. I think the best practice would be to define your own `contextTypes` on your component.

Hopefully, React will relax the contextTypes restriction when they formalize `this.context` in the future.

**Comment by trungpham** [comment]
thanks. I ended up defining my own contextTypes mixin.
I took me a quite a bit of time to figure out what is going until I came
around this blog post.
https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html
