### ISSUE TITLE
Fluxible-router: async navigation and document.title

### ISSUE THREAD

**Issue by Diokuz** [yahoo/fluxible#391]
Fluxible-router *navigationAction* has two phases: NAVIGATE_START and NAVIGATE_SUCCESS. When the action is async, there is a problem with document.title.

History.pushState is used on NAVIGATE_START event, and browser saves title, available at this moment. But the real and proper document.title we get only at NAVIGATE_SUCCESS. The problem here is that when you navigate some routes, and then click&hold `back` button of your browser, you will see something like we do in context menu:

```
Loading...
Loading...
Loading...
Loading...
```
instead of
```
Proper route 1 title
Proper route 2 title
Proper route 3 title
Proper route 4 title
```

Is there any way to fix this? Maybe there is a possibility to delay pushState until NAVIGATE_SUCCESS event? Or replaceState additionally to pushState?

**Comment by mridgway** [comment]
Yes, I think calling `replaceState` to update the title for the current history state on `NAVIGATE_SUCCESS` is the best option here.
