### ISSUE TITLE
need `require('setimmediate');`?

### ISSUE THREAD

**Issue by aun343** [yahoo/fluxible#408]
i found this change
https://github.com/yahoo/fluxible/commit/8ba8de049803e4f9f4a920254292301dcfba5706#diff-4f3db46b990b984ba0e85f6d9725f3f8R15

But there is no `require('setimmediate');` in `callAction.js`.
https://github.com/yahoo/fluxible/blob/8ba8de049803e4f9f4a920254292301dcfba5706/packages/fluxible/utils/callAction.js

because of that, the error message `ReferenceError: setImmediate is not defined` appeared on the console.

**Comment by mridgway** [comment]
I'll get this fixed.

**Comment by mridgway** [comment]
This should be fixed in fluxible@1.0.5

**Comment by aun343** [comment]
🍻
