### ISSUE TITLE
NavLink component no longer supports style property

### ISSUE THREAD

**Issue by ayukoj** [yahoo/fluxible#411]
I am very happy about query param support in NavLink, although style property no longer works.

https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js#L207

I'd guess this line should be `var style = this.props.style` like it does for className.

**Comment by mridgway** [comment]
Fixing now.

**Comment by mridgway** [comment]
This is now fixed in fluxible-router@1.0.0-alpha.2. Thanks for trying out the pre-release and letting use know of the issue!

**Comment by ayukoj** [comment]
Wow, thanks for fixing this so quick! I really appreciate it :)
