### ISSUE TITLE
NAVIGATE_FAILURE payload is still error object

### ISSUE THREAD

**Issue by ayukoj** [yahoo/fluxible#414]
Hi there,

In 1.0.0-alpha1, error from navigateAction doesn't complete navigation and isNavigateComplete property never becomes true.

I noticed that NAVIGATE_FAILURE receives error object but RouteStore expect it to be navigate object.
https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/navigateAction.js#L64

Cheers,

**Comment by mridgway** [comment]
Thanks again for reporting. Fixed in fluxible-router@1.0.0-alpha.3.

**Comment by ayukoj** [comment]
Thank you too! It's working perfect now.
