### ISSUE TITLE
componentContext.executeAction does not run the callback function

### ISSUE THREAD

**Issue by trungpham** [yahoo/fluxible#42]
The callback function never runs when I call the executeAction method on the componentContext. It should behave more like the actionContext.executeAction.

**Comment by mridgway** [comment]
This is actually by design. Actions are meant to be fire and forget from the view. We do not allow the views to know when an action has completed. Instead they should just be listening for changes to stores.

**Comment by trungpham** [comment]
That makes sense. Thanks.
