### ISSUE TITLE
Support for multiple Fluxible apps per page

### ISSUE THREAD

**Issue by dhalbrook** [yahoo/fluxible#420]
I'm currently prototyping a system which uses one Fluxible app to isomorphically generate the site chrome (header, footer) and calls other Fluxible apps to generate the body content.  This works fine on the server of course, but on the client side it seems that the FluxibleContext appears to be a global singleton, causing issues.

For example, the outer (site chrome) app bootstraps its JS just fine, but the inner (page body) app fails in this way:
`
DispatcherContext.js:39 Uncaught Error: Store PersonProfileStore was not registered.getStore @ DispatcherContext.js:39storeStateEach @ DispatcherContext.js:130rehydrate @ DispatcherContext.js:128rehydratePluginTasks @ FluxibleContext.js:345`

As far as I can tell, the store from the one app isn't registered on the context of the other app, and that is where things fall apart.

Has anyone else attempted such a thing?  Any suggestions for handling this?

Many thanks.

**Comment by mridgway** [comment]
We have used multiple `FluxibleContext` instances on a page successfully. Are you calling `createContext()` multiple times on the same Fluxible instance or separate Fluxible instances? If it's a separate Fluxible instance then the registered stores will not be shared.

**Comment by dhalbrook** [comment]
Thanks for the feedback.  It turns out we had some code iterating all possible apps to mount, even if they were not in the purview of the calling service.  This caused the issue.
