### ISSUE TITLE
How to allow running fluxible on IE

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#436]
It might sound stupid but I am looking for a way to allow using Fluxible on Internet Explorer (at least version 11). I need it because I have some users who use IE (some because of their organization policy that does not allow to install Firefox or Chrome). Could you advise me what's the easiest way to sort it out? Do I need to use something like es5-shim?

**Comment by ali1k** [comment]
I could resolve the issue by adding the following patches to my HTML layout:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-sham.min.js"></script>
<script src="https://wzrd.in/standalone/es7-shim@latest"></script>
```

**Comment by redonkulus** [comment]
@ali1k ya we mention in our readme that you will need to use Babel or some other polyfill service for browsers that do not support some ES2015 features https://github.com/yahoo/fluxible/tree/master/packages/fluxible#browser-compatibility

**Comment by ali1k** [comment]
@redonkulus thanks for the pointer. I overlooked that.
 Would be good if there was also an example of adding babel-polyfill to fluxible apps....

**Comment by redonkulus** [comment]
You can take a look at our flux-examples repository to see how it's used.

**Comment by redonkulus** [comment]
Here is a specific one https://github.com/yahoo/fluxible/tree/master/examples/chat
