### ISSUE TITLE
RouteStore::dehydrate serializes too much information

### ISSUE THREAD

**Issue by jlecomte** [yahoo/fluxible#439]
Here is what I get as a result of the Fluxible Router's RouteStore dehydrate function:

```
{
    "context": {
        "dispatcher": {
            "stores": {
                "RouteStore": {
                    "currentNavigate": {
                        "transactionId": 123456789,
                        "url": "\u002Ffoo",
                        "route": {
                            "method": "GET",
                            "path": "\u002Ffoo",
                            "handler": function StoreConnector(props, context) {
                                React.Component.apply(this, arguments);
                                this.state = this.getStateFromStores();
                                this._onStoreChange = null;
                                this._isMounted = false;
                            },
                            "action": function xyz(context, route, done) {
                                [tons of application code]
                            },
                            "name": "foo",
                            "url": "\u002Ffoo",
                            "params": {
                                ...
                            },
                            "query": {
                                ...
                            }
                        },
                        "error": null,
                        "isComplete": true
                    },
                    "routes": null
                },
                ... more stores ...
            }
        }
    },
    "plugins": {}
}
```

I don't think that `handler` and especially `action` should be serialized for each route, since the latter one can be very large.

**Comment by jlecomte** [comment]
This issue blocks us because we are trying to not transpile much on the server now that we can use Node 6, and therefore, ES2015 code gets through, and Safari barfs on it when the page loads.

**Comment by mridgway** [comment]
How else would `handler` and `action` be loaded and attached to the route for client side? I'm surprised this is only breaking in node 6. 

Typically only dynamic routes are dehydrated and using `action` and `handler` in with dynamic routes will not work properly because the dehydrated functions will not have the correct closure context that they need. This is where supplying a `getAction` and `getComponent` plugin to be able to retrieve handlers and actions by strings would be more beneficial.

**Comment by jlecomte** [comment]
I am almost 100% certain that it did not work that way 6 months ago when I migrated Norrin to Fluxible.

Our client side bundle contains the definition for the route handler. It should not need to be inlined.

**Comment by juandopazo** [comment]
@mridgway I think we figured this out and you can close this issue 😄

**Comment by redonkulus** [comment]
@juandopazo what was the issue?

**Comment by juandopazo** [comment]
We're serializing the route handlers when we could be referencing them as strings. I'm figuring out how exactly to get the handler from the string.

**Comment by redonkulus** [comment]
Ok let us know if you have any questions.
