### ISSUE TITLE
FluxibleMixin contextTypes add isRequired?

### ISSUE THREAD

**Issue by ZeikJT** [yahoo/fluxible#44]
Add `isRequired` to the context types?
[/mixins/FluxibleMixin.js#L42-L43](https://github.com/yahoo/fluxible/blob/989cc2ca7aa2b75eb34e28acc5a844b43f17c3d4/mixins/FluxibleMixin.js#L42-L43)

```js
var FluxibleMixin = {
    contextTypes: {
        getStore: React.PropTypes.func.isRequired,
        executeAction: React.PropTypes.func.isRequired
    },
    // ...
```

**Comment by mridgway** [comment]
We still want to support using context as a prop so we won't be making the contextTypes required.
