### ISSUE TITLE
[fluxible-addons-react] batchedUpdatePlugin breaks compatibility with react-native

### ISSUE THREAD

**Issue by malaman** [yahoo/fluxible#443]
Hello,
fluxible-addons-react has inherits as a dependency. 
inherits uses node.js util.inerits function to work in non-browser enviroments.
We are trying to integrate fluxibe/fluxible-addons-react with react-native and usage of the node.utils breaks integration with react-native. 
I've changed inherits module to custom inherits without node imports and integration seems to work fine.
Could you please change this in the fluxible-addons-react package?

**Comment by redonkulus** [comment]
@malaman which version of fluxible-addons-react are you using? We actually depend on the "inherits" modules: https://github.com/yahoo/fluxible/blob/ce8937e47f518b6bedd3c256ab55a621dc07642f/packages/fluxible-addons-react/package.json#L17

**Comment by malaman** [comment]
fluxible-addons-react: 0.2.8

**Comment by redonkulus** [comment]
Oh I see, we can probably find another inherits version on npm that satisifies react-native and doesn't use the native one. You are welcome to open a PR if you want.

**Comment by malaman** [comment]
Ok. I will look for alternatives and open PR, if find something.

**Comment by koulmomo** [comment]
surprised this is an issue

thanks to https://github.com/facebook/react-native/pull/2208, react-native should fallback to the `browser` field of packages if one is [specified](https://github.com/isaacs/inherits/blob/316042ae8333b55bbbbc39315cf5b6a90aa73aad/package.json#L16).

I would check if explicitly adding a `react-native` field to the `inherits` package.json that points to the `browser` impl fixes it for you and if so PR-ing that change to inherits.

**Comment by malaman** [comment]
Hi again, 
I've made additional debugs of the issue.
The reason of errors is not the inherits module, but batchedUpdatePlugin in the fluxible-addons-react.
If i've commented batchedUpdatePlugin from the module.exports in the fluxible-addons-react/index.js, and receive no errors.

**Comment by malaman** [comment]
If this is still actual, we've managed to run fluxible app with react-native.

https://github.com/malaman/fluxible-react-native

**Comment by malaman** [comment]
Currently we import `connectToStores` and `provideContext` directly from source files as workaround for batchedUpdatePlugin issue. 
```
import connectToStores from 'fluxible-addons-react/connectToStores';
import provideContext from 'fluxible-addons-react/provideContext';
```
I've updated example repository (https://github.com/malaman/fluxible-react-native) in case if someone will face same issue.
