### ISSUE TITLE
How to disable onScroll replaceState ?

### ISSUE THREAD

**Issue by Diokuz** [yahoo/fluxible#448]
IOS safari has a bug https://forums.developer.apple.com/thread/36650
And we have a problem, because each scroll leads to history.replaceState.

How to disable it? We dont need scroll handling at all.

Maybe just make some `if (options.enableScroll)` here:

https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/handleHistory.js

?

**Comment by mridgway** [comment]
A refactor for scroll state should be discussed in #336. Since this specific issue is resolved in #450 for now, I will close this issue.
