### ISSUE TITLE
Doc links point to old github location

### ISSUE THREAD

**Issue by Sampo123** [yahoo/fluxible#455]
I was trying to update from old flux-router-component to current fluxible-router but I run into many documentation links being broken. 

From this page https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/UPGRADE.md

At least the quick start link and the handleRoute link point to the old GitHub location. 

(though I managed to find the pages in question but still for someone else that might be annoying)

(fixed typo)

**Comment by redonkulus** [comment]
Ya thats mainly because we moved to a "monorepo", I can fix the doc links in that document. Did you see broken links in other docs?

**Comment by redonkulus** [comment]
Fixed https://github.com/yahoo/fluxible/commit/374fabb1d2c2b71edb62d454116f69d032766189
