### ISSUE TITLE
[fluxible-reducer-store] internal state should not be able to be manipulated directly

### ISSUE THREAD

**Issue by pwmckenna** [yahoo/fluxible#456]
```js
reducers: {
    SET_STATE: state => {
        state.foo = 'bar';
        return state;
    }
}
```

while it is sort of a code smell imo for the reducers to change the internal state directly, but the real issue that this causes is the first time this is executed, it changes the `initialState` field on the spec passed into `createReducerStore`, so if you create a context, dispatch this event, then create another context, the initialState is now the first's context's post-dispatch state.

Calling object.freeze on the initial state might work (assuming its an object), but doesn't do much to ensure reducers are pure functions.

**Comment by mridgway** [comment]
Yeah, you would have to do a deep freeze for it to be reliable I think. I'd be fine with this change if it's only done in development.

**Comment by pwmckenna** [comment]
Couldn't come up with a solution that could handle using immutable for the state (or any none bare object), and I don't think assuming the type of the state would be good...so I'm going to close this out.
