### ISSUE TITLE
Are Yahoo still using fluxible?

### ISSUE THREAD

**Issue by ptomasroos** [yahoo/fluxible#459]
I saw a public announcement that Yahoo has just released a new web page with redux and SSR.
I'm wonder whats the strategy ahead, is yahoo still looking to maintain their own universal flux implementation or looking for alternatives?

**Comment by redonkulus** [comment]
@ptomasroos Yahoo is still committed to Fluxible. In fact, we just launched Yahoo Sports and Finance on it yesterday. 

The Finance mobile web site released a version of it on Redux. However, the desktop site is using Fluxible. Why would the same site use two different frameworks? Its complicated and not something our team had a decision in. But was a good way to see the pros and cons of a different implementation. 

So fear not, we are still using it and launching even more sites on it. Thanks!

**Comment by ptomasroos** [comment]
All right. Congrats on new launches and thanks for the feedback @redonkulus

**Comment by longlho** [comment]
Disclaimer: my team worked on the Finance MW experience using Redux

@ptomasroos fear not. Yahoo's a huge company and there're a lot teams constantly evaluating/using different technologies/frameworks. We got teams using Ember, Angular, Redux, Fluxible and the nice part is that we share our findings and try to make things better in general :) Fluxible does have a whole team behind thou so it doesn't get more legit than that ;)

**Comment by ptomasroos** [comment]
@longlho you should def consider blogging about your experiences running redux universal vs fluxible. I think its a very interesting topic and something the community def could benefit from even though you might be biased. :)
