### ISSUE TITLE
update to react-hot-loader v3.0

### ISSUE THREAD

**Issue by ali1k** [yahoo/fluxible#507]
Do you have any plan to update to react-hot-loader v3.0? it seems to need a different config as explained in https://thesabbir.com/hot-reloading-react-stateless-components/

**Comment by redonkulus** [comment]
@ali1k certainly not opposed to it. If you would like to test it out and issue a PR, we would be appreciative.

**Comment by jamesjjk** [comment]
@ali1k Have you had any luck with this? For me its throwing a promise error in fluxible when I wrap the component with the hotLoader appContainer.

**Comment by aldodevs** [comment]
Any updates?

**Comment by redonkulus** [comment]
@jamesjjk what error were you seeing?
