### ISSUE TITLE
[fluxible-router] Convert CreateNavLinkComponent to ES6 Class based implementation

### ISSUE THREAD

**Issue by nim23** [yahoo/fluxible#508]
I have recently tried to port our React based app to Preact, to see how many more bytes I could shave off. For the most part it was quite easy to do. The only hiccup I came so far was that Preact doesn't really support React.CreateClass and [CreateNavLinkComponent](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js#L69) relies on React.CreateClass. Is there any reason this can't be converted to an ES6 class based implementation. I totally understand if this is out of the project's scope.

**Comment by mridgway** [comment]
It would be difficult to set up the transpilation for the ES6 class syntax in the short term, but it should be feasible to make it an ES5 class which should still be compatible with Preact.

**Comment by chrishinrichs** [comment]
This was caused by an incompatibility in `preact-compat` which was just fixed: https://github.com/developit/preact-compat/issues/248

**Comment by nim23** [comment]
@chrishinrichs thanks.
