### ISSUE TITLE
React.createClass deprecated on React 15.5.0 and above

### ISSUE THREAD

**Issue by J-Dickson** [yahoo/fluxible#528]
### Information about the Issue

React.createClass is deprecated in React 15.5.0, therefore the React.createClass in NavLink causes a deprecation warning for any users on this version of React.

This will become a breaking change in React 16.0.0.

Are there plans to make this change in the project?

Thanks

**Comment by kaesonho** [comment]
This is an automatically generated message.

kaesonho@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by redonkulus** [comment]
Thanks for the report. We need to migrate all the code to es6 classes but that will take time if the components use mixins. In the meantime, we can use their new `react-create-class` package to remove the spam.

**Comment by J-Dickson** [comment]
Hi, thanks for your reply. Would you like me to do a PR?

**Comment by redonkulus** [comment]
Sure thing. Akon with fluxible-router, we will need fluxible-addons-react updated as well if you can do that too.

**Comment by redonkulus** [comment]
Related https://github.com/facebook/react/issues/9384

**Comment by J-Dickson** [comment]
Here is the PR: https://github.com/yahoo/fluxible/pull/530

**Comment by redonkulus** [comment]
Closed via https://github.com/yahoo/fluxible/pull/530

**Comment by redonkulus** [comment]
@J-Dickson fluxible-router@1.1.0 and fluxible-addons-react@0.2.10 published with these changes. Thanks!
