### ISSUE TITLE
Replace createReactClass with ES6 classes

### ISSUE THREAD

**Issue by alexparish** [yahoo/fluxible#546]
The module _create-react-class_ is a dependency of both _fluxible-addons-react_ and _fluxible-router_ and as such will bloat any projects that consume these packages.

Instances of createReactClass should be replaced with ES6 classes that extend React.Component such that the dependency on the _create-react-class_ module can be removed.

**Comment by redonkulus** [comment]
@alexparish Good point.  For fluxible-addons-react that package is actually only used for testing, so we could move the dependency to devDependencies to avoid the extra bloat.

For fluxible-router, we could refactor that away too. We would have to ensure we are not leveraging mixins or anything to ensure we do not break functionality.

**Comment by redonkulus** [comment]
Published in fluxible-addons-react@0.2.13

**Comment by alexparish** [comment]
This issue seems more pressing now React 16 has launched. 

This latest version of React has removed the dependency on _create-react-class_ but `fluxible-router` still has a dependency on it.

**Comment by redonkulus** [comment]
@alexparish Shouldn't be an issue with React 16 because we are using the [create-react-class package](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/package.json#L28) instead of relying on React.createReactClass directly.

**Comment by alexparish** [comment]
@redonkulus Sure, I understood that nothing will break. 

My concern was the bloat of bringing in that extra package. Removing the dependency (and using ES6 classes instead) would shave 12.5K from my bundle. Not huge, but it seems an unnecessary dependency. 

I will look into creating a PR for this if I can find time.

**Comment by mridgway** [comment]
I believe there is only one place that uses `createReactClass` at this point: https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js

I migrated everything to use ES5 classes in https://github.com/yahoo/fluxible/commit/9c46478e2fb9cb11f942a608db969af2e425abcb but did not migrate that one case for a reason I can't remember. It may be a backward incompatibility but I can't remember.

**Comment by alexparish** [comment]
I have created a PR to remove that final instance of `createReactClass`

**Comment by alexparish** [comment]
Updated PR created: https://github.com/yahoo/fluxible/pull/586
