### ISSUE TITLE
Error: Url does not match any routes

### ISSUE THREAD

**Issue by ajayak** [yahoo/fluxible#547]
/opt/app/node_modules/fluxible/lib/FluxibleContext.js:263
                    throw err;
                    ^

Error: Url '/start-review/https://channel9.msdn.com/Blogs/One-Dev-Minute/Building-a-Pet-Recognition-Door-Using-Windows-10-IoT-Core' does not match any routes
    at navigateAction (/opt/app/node_modules/fluxible-router/lib/navigateAction.js:40:28)
    at Immediate.<anonymous> (/opt/app/node_modules/fluxible/utils/callAction.js:20:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lingyan** [comment]
@ajayak You can customize `componentActionErrorHandler` to gracefully handle this error: https://github.com/yahoo/fluxible/blob/master/packages/fluxible/docs/api/Fluxible.md#optionscomponentactionerrorhandler

The `defaultComponentActionHandler` provided by Fluxible simple throws the error (https://github.com/yahoo/fluxible/blob/master/packages/fluxible/lib/Fluxible.js#L18-L24), thats why you are seeing this.

**Comment by mridgway** [comment]
Seems like this may be a malformed URL that is being passed to the router. For external links you should not use `navigateAction` or `Link` components, instead just use `<a>` tags.
