### ISSUE TITLE
Support registering services that return promises

### ISSUE THREAD

**Issue by gilligan** [yahoo/fluxible#556]
From what I can tell services which are declared using the fetchr as described [here](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-plugin-fetchr/README.md#registering-your-services) still won't work with services that implement Promise returning CRUD methods. Am I correct? Are there any plans to change that? Is that feasible. 

Thanks.

**Comment by mridgway** [comment]
I believe the plugin does support Fetchr services that use Promises. I believe the plugin's methods (read, create, etc.) are straight proxies to the Fetchr methods.

**Comment by gilligan** [comment]
@mridgway  have a look at https://github.com/yahoo/fetchr/issues/111

**Comment by mridgway** [comment]
Ah, I see. I thought you were asking about calls to the services, not the services themselves. Looks like this is indeed not supported currently.

**Comment by gilligan** [comment]
Too bad.
