### ISSUE TITLE
Some properties are not showing.

### ISSUE THREAD

**Issue by ccruz2886** [yahoo/fluxible#557]
### Expected behavior
- All properties in `this.currentState = myState;` should be sent to the components.

### Actual behavior
- Some properties are not sent to the components that are connected to the store.

### Information about the Issue
- I notice while I print `console.log('myObj', myObj);` all object are printed, but when I log the properties that are result of the `context.getStore('MyStore').getState()` some properties are missing.

### Steps to reproduce the behavior

  1. ... The result of the query API, dispatch of `SOMETHING_HANDLER` handler.
  2. ... Console.log(this.currentState)
  3. ... Console.log(this.props)

- Both logs should be the same.

**Comment by redonkulus** [comment]
Could you provide some code snippets on how you are using connectToStores? Thats generally what you declare to be passed in as props to your component.
