### ISSUE TITLE
Using constants for handlers

### ISSUE THREAD

**Issue by wiredprairie** [yahoo/fluxible#56]
If I were to create a simple store:

    var AuthenticationStore = createStore({
        storeName: 'AuthenticationStore',
        handlers: {
        
        }
    });

And want to add a handler, that's easy enough to declare:

    handlers: {
        'SIGNOUT': 'handleSignout'
    }

But, what I don't see a way to do is to use a "constant" value as the name of the action being handled. I want to declare them in advance and use them consistently and safely across my code base rather than relying on me typing string values consistently:

    var AuthActions = {
        SIGNOUT: 'SIGNOUT';
    };

Then, I could do something like (inspired by Fluxxor), where there is an `initialization` function that allows the actions/handlers to be bound (here, they're bound as KV pairs):

    initialize: function() {        
        this.bindActions(
          AuthActions.SIGNOUT, this.handleSignout
        );
    }

**Comment by wiredprairie** [comment]
For now, I created a simple function to mimic the behavior of Fluxxor's `handlers`:

    function toObject(/* in pairs */) {
        if (arguments.length % 2 !== 0) {
            throw new Error("Values must be in pairs")
        }
        var result = {};
        for(var i = 0, len = arguments.length; i < len; i += 2) {
            result[arguments[i]] = arguments[i + 1];
        }
        return result;
    }

Then I just use it like:

    handlers: toObject(
        AuthActions.SIGNOUT, 'onSignout'
    )

It's an acceptable work-around, but I'd like to see patterns like this incorporated into the core library (which may in fact be technically from the [Dispatcher](https://github.com/yahoo/dispatchr))?

**Comment by mridgway** [comment]
I don't think this is something we would provide in the library since it is more of a JS level issue than a library issue.

I think the best solution for this is ES6's [computed property keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_6).

**Comment by wiredprairie** [comment]
Is there isn't anything in this package that requires anything beyond ES5 currently?

**Comment by mridgway** [comment]
No, there isn't. But we fully plan on moving to ES6 in the near future.

**Comment by wiredprairie** [comment]
You're planning on requiring ES6 for users of this code? OK, I still think this pattern, regardless of ES6 would allow a few simple freedoms not offered by your library currently.

**Comment by mridgway** [comment]
Not require, but I see this as more of a general issue than a framework specific issue and therefor solvable via another npm module (if it doesn't exist already, you should create it!) or language features as in ES6.
