### ISSUE TITLE
Should dispatch NAVIGATE_FAILURE if action is not able to resolve

### ISSUE THREAD

**Issue by lingyan** [yahoo/fluxible#615]
https://github.com/yahoo/fluxible/blob/7ad54c83ee9694af8733918b32fc38bdec057ecf/packages/fluxible-router/src/lib/navigateAction.js#L49-L54

There are two cases here:
* `action` is not specified (`route.action` is empty): Fine to dispatch `NAVIGATE_SUCCESS`
* `action` is specified but unable to resolve into a function: **SHOULD dispatch `NAVIGATE_FAILURE`**

We should fix the second case to dispatch failure event.  Dispatching success event masks the problem and makes debugging hard.

**Comment by redonkulus** [comment]
This was fixed in both fluxible-router@1.x. and 2.x major versions.

**Comment by lingyan** [comment]
Yeah! thanks @redonkulus 🥇
