### ISSUE TITLE
Update React lifecycle methods

### ISSUE THREAD

**Issue by BryceV** [yahoo/fluxible#636]
In a couple components there are old react lifecycle methods. In my case it was componentWillReceiveProps in connectToStores:

<img width="523" alt="Screen Shot 2020-05-20 at 8 56 21 AM" src="https://user-images.githubusercontent.com/9063864/82468805-18243300-9a78-11ea-8344-d865745646e1.png">

**Comment by pablopalacios** [comment]
@redonkulus this is a duplicate of #587 and I'm already solving it. Feel free to close it.

**Comment by redonkulus** [comment]
Sounds good to me.
