### ISSUE TITLE
react-dependency fails in older npm

### ISSUE THREAD

**Issue by gabor** [yahoo/fluxible#65]
hi,

if you use node-0.10, and the npm bundled with it, then this fails:

    npm install react@0.13.0 fluxible@0.2.9
    
    npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer fluxible@0.2.9 wants react@>=0.12.0 <=0.13.x

on node-0.12 it works.

im guessing this is a npm bug that was fixed in https://github.com/npm/node-semver/commit/c835c1ddef4a3d0e27c31fafa8098150815ef72b .

but, considering node-0.10 is still used, could fluxible perhaps use a different "backward" compatible dependency-version?

im not sure how exactly this works, but perhaps instead of "<=0.13.x" go with "<0.14" or something?

**Comment by gabor** [comment]
something like this

https://github.com/gabor/fluxible/commit/d223b6bd8b9c70f0b8a8dbd1910792bdffaba3ee

**Comment by gabor** [comment]
btw. the same issue is in flux-router-compontent too.

**Comment by mridgway** [comment]
Yup, we found this issue as well. So `>=0.12.0 <0.14` works correctly?

**Comment by mridgway** [comment]
So the issue with <0.14 is that in npm 1.x, it would include pre-releases like 0.14.0-rc1, which isn't what we want. Either we just settle with that being OK and potentially breaking people or we bump our minor version and lock on 0.13.x.

**Comment by mridgway** [comment]
Alright, so here's the plan: we're going to release a new minor version of Fluxible (0.3.0) with dependency as 0.13.x. Users of React 0.12 will still work with the current Fluxible version (0.2.9). Users of React 0.13 should update to Fluxible 0.3.0.

**Comment by mridgway** [comment]
We've released v0.3.0 that will use only React@0.13.x. This should give you an upgrade path for using Fluxible with npm 1.x.
