### ISSUE TITLE
Wait to render component until data is fetched

### ISSUE THREAD

**Issue by captainill** [yahoo/fluxible#7]
I'd like to be able to show a loader in response to an action while data is fetched and wait for the response to render a component. This is a hot topic over in the react-router repo. Have you guys talked about this? Is there a solution currently?

**Comment by jardakotesovec** [comment]
While investigating what the current options are. I came across this example https://github.com/rackt/react-router/blob/master/docs/api/run.md#stateroutes

Triggering fetch actions from Route objects seems like nice solution and it can be traversed before actual rendering. Assumption basically is that URL should represent which view-controllers will show up. If react component makes decision to show something else based on some other data (like parameter in url or retrieved data).. it would go wrong..

**Comment by mmahalwy** [comment]
@mridgway can you provide an example of the static hierarchy to wait for?

I think something that could be powerful is to always have a flag of 'wait for this action to finish, every time'  or 'these must finish' before renderToString.
