### ISSUE TITLE
done() in storeListeners

### ISSUE THREAD

**Issue by MrOrz** [yahoo/fluxible#76]
In https://github.com/yahoo/fluxible/blob/master/lib/FluxibleMixin.js#L18 , https://github.com/yahoo/fluxible/blob/master/lib/FluxibleMixin.js#L32 the store listeners invoked `done()`.

As far as I know the store listeners should invoke `this.setState` to reflect the changes in store to the component itself. `done()` here seems a bit strange there.

**Comment by jedireza** [comment]
Yes. We need to update those comment blocks.

**Comment by mridgway** [comment]
Fixed. Thanks for notifying us!

**Comment by MrOrz** [comment]
:+1: for the timely fix!
