### ISSUE TITLE
Namespacing plugins

### ISSUE THREAD

**Issue by jedireza** [yahoo/fluxible#79]
Currently plugins add functionality to the root of `context`. This makes it easy for plugins to pollute `context` or collide features with one another.

Also in larger apps it can get hard to know which plugin is responsible for a specific piece of functionality. I'd like to see plugin functionality to be namespaced. `context.pluginName.someFeature(...)` as an example.

Plugin names should be unique and we should throw during `app.plug({ ... })` if a a plugin with the same name has already been registered.

If you take a look at `react-router@0.13.x`, they're kind of following a similar idea in that `context.router` contains all their functionality.

**Comment by mridgway** [comment]
Sounds reasonable to me. Would love to hear more about how people are using plugins in the wild.

**Comment by mridgway** [comment]
plug*Context() functions would now return an object that contains their functions rather than modifying the context object directly.

**Comment by cesarandreu** [comment]
I'm currently using a plugin to allow promises in actions, another to add a wrapped fetch (so I can add stuff like csrf token to all requests getting sent, and overwrite how the csrf token is taken depending on environment), and another to abstract react-router and add the instance to my action context. 

Something I like about the current approach is I can monkey-patch stuff (e.g. executeAction).

I haven't built anything big enough with Fluxible such that this would be a problem, though.

**Comment by alexaivars** [comment]
Currently I don't se the need of having that many plugins that this would result in a problem. Currently I'm working on a few big app but only using plugins for easy access to analytics tracking, a remote service interface in actions and sharing environment variables between the server and client.

**Comment by jedireza** [comment]
Should we close this one too?

**Comment by redonkulus** [comment]
@jedireza  :+1:
