### ISSUE TITLE
using data from http request

### ISSUE THREAD

**Issue by Agrosis** [yahoo/fluxible#80]
I'm using the react-router example with express as a server, and in order to render the page, I need to grab a header from the incoming HTTP request and supply it.

To do this, I execute an action first that puts some data in a store, and then I render the React router inside the callback, so when the router is rendered, it has access to that data.

I'm wondering if this is actually a safe operation, and whether there are any side effects I'm unaware of? Or is there a better way to do this entirely?

```
server.use(function(req, res, next){
  var context = app.createContext();
  var token = req.cookies.token || "";

  var router = Router.create({
    routes: app.getComponent(),
    location: req.path,
    transitionContext: context
  });

  context.executeAction(setToken, {token:token}, function(){
    router.run(function (Handler, state){
      var exposed = 'window.App=' + serialize(app.dehydrate(context)) + ';';

      var Component = React.createFactory(Handler);
      var html = React.renderToStaticMarkup(HtmlComponent({
          state: exposed,
          markup: React.renderToString(Component({context:context.getComponentContext()})),
          context: context.getComponentContext()
      }));

      res.send("<!doctype html>" + html);
    });
  });

});
```

The setToken action just dispatches an event that makes a store I have set a field to the provided value.

**Comment by mridgway** [comment]
Seems totally legit to me :+1:.  Just make sure that if that value affects rendering that the token is passed down to the client via your store's dehydrate function.

**Comment by Agrosis** [comment]
Yeah, I do, thanks for the help! :smile:
