### ISSUE TITLE
Fluxible#rehydrate() arguments should contain callback in the doc

### ISSUE THREAD

**Issue by MrOrz** [yahoo/fluxible#81]
https://github.com/yahoo/fluxible/blob/master/docs/api/Fluxible.md#rehydratestate

In the doc it only specifies state as its argument. However, we cannot use `rehydrate` without giving it a callback. We need the context passed in the callback as well. I think we need to put these in the doc.

**Comment by jedireza** [comment]
Thanks. This should be corrected.

**Comment by mridgway** [comment]
Updated the doc. Thanks for bringing this to our attention @MrOrz!
