### ISSUE TITLE
React-router and actions

### ISSUE THREAD

**Issue by Spy-Seth** [yahoo/fluxible#86]
I'm trying to do some test with `fluxible` and `react-router` and I can't figure how `react-router` and flux actions work together.

If I use `fluxible` without `react-router` (with the recomended router). A route is associated to an action. Action who can load the needed data to populate some store. And then these data is used to render the app. This is simple and works well.

Now I'm trying to do the same with `react-router`, but as we associate a route with a component. I do not see where call my action to prepare the data in my store.

For now, I execute the action in the `getInitialState` method of my component:
```javascript
    getInitialState: function () {
        this.executeAction(hotelListUpdate, {/* ... */});

        return this.getState();
    },
```

It's work, but trigger two render of the component on the screen: the first without the data, the second with.

Have you any clue?

**Comment by mridgway** [comment]
If you are doing server rendering, you will not be able to initiate actions from with React components because rendering is synchronous and actions are not. Ideally, you use the `Router.run()` callback to execute your actions before you call `React.render`.

Take a look at the [react-router flux doc](https://github.com/rackt/react-router/blob/f3a44f1bc898848d553c39e7aa53a70d0e91ec11/docs/guides/flux.md#accessing-route-and-params-from-action-creators) which has some examples of doing this or our [flux-example](https://github.com/yahoo/flux-examples/blob/master/react-router/server.js#L24).

**Comment by Ambroos** [comment]
Another approach I've been using is adding a data fetching method to the statics of my route handlers.

This does require you to use your route handlers as 'controller' components. They keep the data they need in their props and make sure it's available, then decide which other components to render. From there on everything is done with props only. (Which is interesting performance-wise too if you use Immutable for your data.)

It's something I adapted from examples I found spread around issues here and for React-Router. Took me a few weeks as it was for my very first JavaScript project and I set the bar pretty high, but it works:

// utils/prepareData.js
```javascript
import async from 'async';
import filter from 'lodash/collection/filter';
import reduce from 'lodash/collection/reduce';

export default function prepareData(context, routerState, cb) {
    cb = cb || function noop() {};

    let fetchDataRoutes = filter(routerState.routes, function(route) {
        return route.handler.prepareData;
    });
    if (fetchDataRoutes.length === 0) {
        return cb();
    }

    let dataFetchers = reduce(fetchDataRoutes, function(result, route) {
        let fetcher = route.handler.prepareData
            .bind(null, context, routerState.params, routerState.query);
        result[route.name] = fetcher;
        return result;
    }, {});

    async.parallel(dataFetchers, cb);
}

```

// server.js
```javascript
import prepareData from './utils/prepareData';

// ...

server.use((req, res, next) => {
    // Create the context with app config.
    let context = app.createContext({
        config: config
    });

    // Let the Router run.
    Router.run(app.getComponent(), req.path, (Handler, state) => {
        context.executeAction(navigateAction, state, () => {

            // prepareData checks the active route handlers and lets them execute
            // any data fetching they may have to do before starting React rendering
            prepareData(context.getActionContext(), state, (err) => {
                if (err) {
                    return next(err);
                }

                let exposedState = 'window.App=' + serialize(app.dehydrate(context)) + ';';

                // We let React create the application HTML
                let component = React.createFactory(Handler);
                let markup = React.renderToString(React.createElement(
                    FluxibleComponent,
                    { context: context.getComponentContext() },
                    component()
                ));

                // We get some metadata that is only relevant for server-side applications
                // and render it into the HTML here.
                let title = DocumentTitle.rewind();
                let status = NestedStatus.rewind();
                let html = React.renderToStaticMarkup(htmlComponent({
                    title: title,
                    state: exposedState,
                    markup: markup
                }));

                res.status(status).send('<!DOCTYPE html>' + html);
            });
        });
    });
});
```

// Component
```javascript
'use strict';

function prepareData(context, params, query, done) {
    async.parallel(
        [ // These contain the actions we want to do in parallel to fetch data.
            (loadDataDone) => context.executeAction(loadSomeData, params.id,
                () => {
                    loadDataDone();
                }),
            (loadDataDone) => context.executeAction(loadSomeOtherData, query.option,
                () => {
                    loadDataDone();
                }),
        ],
        // Callback executed when actions above are both done.
        () => {
            let myStore = context.getStore(MyStore);

            let data = store.getDataById(params.id);
            // Maybe do something with the data from the store.
            async.parallel(
                [
                    (processActionDone) => context.executeAction(setSomethingSpecial, {
                            data: data // The data we needed.
                        }, processActionDone),
                    (processActionDone) => context.executeAction(anotherConfig, {
                            moreData: doSomething(data)
                        }, processActionDone),
                ],
                done // The done here is the callback we got from prepareData
            );       // We need to do this so the server knows when we're ready to render.
        }
    );
}

let MyHandlerComponent = React.createClass({
    mixins: [ FluxibleMixin ],
    contextTypes: {
        router: React.PropTypes.func,
        getStore: React.PropTypes.func,
        executeAction: React.PropTypes.func,
    },
    statics: {
        storeListeners: [ MyStore ],
        prepareData: prepareData, // We pass it in here because it's a bit long.
    },

    getInitialState() {
        // ...
    },

    onChange() {
        // ...
    },

    render() {
        // Here you use your state (from stores) to decide what components to render.
        // For example, if you're on the client and the stores don't have the data, show a loading thing.
        // Just pass the data the components need as props and avoid UI logic here.
        //
        // This component basically becomes a controller.
        // The other components only use props (or a very basic state, nothing from stores).
    },

    componentWillMount() {
        if (typeof window !== undefined) { // Don't run this on the server
            // Here you basically do the same things you do in prepareData:
            // You check the data you have, start actions to get the rest.
        }
    },

    componentWillReceiveProps() {
        // Called when we change route to the same route handler but with different params/query.
        // Again you may have to do some data fetching.
    },
});

export default MyHandlerComponent;
```

It's not ideal. The biggest downside is that if you're not careful you'll feel like writing the same fetching code three times, in `prepareData`, `componentWillMount` and `componentWillReceiveProps`. And it's not the most robust/flexible option. But it allows you to keep your data fetching for every route/handler in a single place.

Considering how complex server rendering can get (you always have to know when you're 'ready' to render), it's a good start I think.

**Comment by Spy-Seth** [comment]
Thanks for you reply. 

I was thinking about something really close that what your suggest @Ambroos. Thanks to you for the complete code! It's helps a lot.

Is fluxible cannot help by providing a structured way to do this ?

**Comment by ChristopherBiscardi** [comment]
@Spy-Seth We are using an approach very similar to [the react-router fluxible example](https://github.com/yahoo/flux-examples/blob/master/react-router/actions/navigate.js) in which we treat the `navigate` action as a complete re-render of the page (say, on the server) and we have some more dynamic, granular actions which handle smaller pieces of the Stores on the client. (Consider the difference between a `ThingPage`, which has to fetch from multiple sources, and a `deleteThing` action, which could be a smaller action).

We also trigger `navigate` when using react-router's `transitionTo`.

**Comment by Spy-Seth** [comment]
For know the suggested approach by @Ambroos seem feel our need. 

The only problem is with de 0.4 version of fluxible. Some API change breaks things. I haven't the time too lock closer for know. So wait & see.

**Comment by Ambroos** [comment]
@Spy-Seth Everything should keep working in v0.4.x, I've just made the switch and besides some minor deprecation warnings you're fine if you keep doing things 'the old way'.

If you want to use all the new goodies in v0.4.x, there's a bit more work needed. You need to move your `prepareData` function to the outermost wrapped function (when using `connectToStores` or `provideContext`) in order to have it picked up by the helper.

**Comment by laser** [comment]
@Ambroos - Out of curiosity, which function is `the outermost wrapped function` that you're referring to? I ask because I've recently upgraded from 0.3.x to 0.4.3 and started using `connectToStores` and `provideContext`, which broke my earlier solution (which looked quite similar to yours, posted above).

**Comment by laser** [comment]
Actually, I get it. connectToStores simply creates a new component that proxies to your original component. I reckon you could augment its return value with your loader function.
